######################################################################
# Automatically generated by qmake (2.01a) Tue Jun 5 21:17:40 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += citymodel.h
SOURCES += citymodel.cpp main.cpp
