######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 24 12:01:23 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += spinbox.cpp
