######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 4 00:03:45 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h stringlistmodel.h
SOURCES += main.cpp mainwindow.cpp stringlistmodel.cpp
TRANSLATIONS += model_zh.ts
