/* soapStub.h
   Generated by gSOAP 2.8.14 from jnuy.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapStub_H
#define soapStub_H
#define SOAP_NAMESPACE_OF_ns1	"http://jinanwater.cn/"
#include "stdsoap2.h"
#if GSOAP_VERSION != 20814
# error "GSOAP VERSION MISMATCH IN GENERATED CODE: PLEASE REINSTALL PACKAGE"
#endif

#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE_xsd__anyType
#define SOAP_TYPE_xsd__anyType (9)
typedef struct soap_dom_element xsd__anyType;
#endif
#ifndef SOAP_TYPE_xsd__anyAttribute
#define SOAP_TYPE_xsd__anyAttribute (11)
typedef struct soap_dom_attribute xsd__anyAttribute;
#endif

/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif





#ifndef SOAP_TYPE__ns1__GetTime
#define SOAP_TYPE__ns1__GetTime (13)
/* ns1:GetTime */
struct _ns1__GetTime
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__ns1__GetTimeResponse
#define SOAP_TYPE__ns1__GetTimeResponse (14)
/* ns1:GetTimeResponse */
struct _ns1__GetTimeResponse
{
	LONG64 GetTimeResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:long */
};
#endif

#ifndef SOAP_TYPE__ns1__GetDNS
#define SOAP_TYPE__ns1__GetDNS (16)
/* ns1:GetDNS */
struct _ns1__GetDNS
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__ns1__GetDNSResponse
#define SOAP_TYPE__ns1__GetDNSResponse (17)
/* ns1:GetDNSResponse */
struct _ns1__GetDNSResponse
{
	char *GetDNSResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__GetHostInfo
#define SOAP_TYPE__ns1__GetHostInfo (18)
/* ns1:GetHostInfo */
struct _ns1__GetHostInfo
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__ns1__GetHostInfoResponse_GetHostInfoResult
#define SOAP_TYPE__ns1__GetHostInfoResponse_GetHostInfoResult (20)
/* ns1:GetHostInfoResponse-GetHostInfoResult */
struct _ns1__GetHostInfoResponse_GetHostInfoResult
{
	struct soap_dom_element __any;	/* external */
	struct soap_dom_element __mixed;	/* external */
};
#endif

#ifndef SOAP_TYPE__ns1__GetHostInfoResponse
#define SOAP_TYPE__ns1__GetHostInfoResponse (19)
/* ns1:GetHostInfoResponse */
struct _ns1__GetHostInfoResponse
{
	struct _ns1__GetHostInfoResponse_GetHostInfoResult *GetHostInfoResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:GetHostInfoResponse-GetHostInfoResult */
};
#endif

#ifndef SOAP_TYPE__ns1__CheckSHA1
#define SOAP_TYPE__ns1__CheckSHA1 (22)
/* ns1:CheckSHA1 */
struct _ns1__CheckSHA1
{
	char *Text;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__CheckSHA1Response_CheckSHA1Result
#define SOAP_TYPE__ns1__CheckSHA1Response_CheckSHA1Result (24)
/* ns1:CheckSHA1Response-CheckSHA1Result */
struct _ns1__CheckSHA1Response_CheckSHA1Result
{
	struct soap_dom_element __any;	/* external */
	struct soap_dom_element __mixed;	/* external */
};
#endif

#ifndef SOAP_TYPE__ns1__CheckSHA1Response
#define SOAP_TYPE__ns1__CheckSHA1Response (23)
/* ns1:CheckSHA1Response */
struct _ns1__CheckSHA1Response
{
	struct _ns1__CheckSHA1Response_CheckSHA1Result *CheckSHA1Result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:CheckSHA1Response-CheckSHA1Result */
};
#endif

#ifndef SOAP_TYPE__ns1__ToBASE64
#define SOAP_TYPE__ns1__ToBASE64 (26)
/* ns1:ToBASE64 */
struct _ns1__ToBASE64
{
	char *Text;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__ToBASE64Response_ToBASE64Result
#define SOAP_TYPE__ns1__ToBASE64Response_ToBASE64Result (28)
/* ns1:ToBASE64Response-ToBASE64Result */
struct _ns1__ToBASE64Response_ToBASE64Result
{
	struct soap_dom_element __any;	/* external */
	struct soap_dom_element __mixed;	/* external */
};
#endif

#ifndef SOAP_TYPE__ns1__ToBASE64Response
#define SOAP_TYPE__ns1__ToBASE64Response (27)
/* ns1:ToBASE64Response */
struct _ns1__ToBASE64Response
{
	struct _ns1__ToBASE64Response_ToBASE64Result *ToBASE64Result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:ToBASE64Response-ToBASE64Result */
};
#endif

#ifndef SOAP_TYPE__ns1__FromBASE64
#define SOAP_TYPE__ns1__FromBASE64 (30)
/* ns1:FromBASE64 */
struct _ns1__FromBASE64
{
	char *Text;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__FromBASE64Response_FromBASE64Result
#define SOAP_TYPE__ns1__FromBASE64Response_FromBASE64Result (32)
/* ns1:FromBASE64Response-FromBASE64Result */
struct _ns1__FromBASE64Response_FromBASE64Result
{
	struct soap_dom_element __any;	/* external */
	struct soap_dom_element __mixed;	/* external */
};
#endif

#ifndef SOAP_TYPE__ns1__FromBASE64Response
#define SOAP_TYPE__ns1__FromBASE64Response (31)
/* ns1:FromBASE64Response */
struct _ns1__FromBASE64Response
{
	struct _ns1__FromBASE64Response_FromBASE64Result *FromBASE64Result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:FromBASE64Response-FromBASE64Result */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREhbgs
#define SOAP_TYPE__ns1__get_USCOREhbgs (34)
/* ns1:get_hbgs */
struct _ns1__get_USCOREhbgs
{
	char *str;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREhbgsResponse_get_USCOREhbgsResult
#define SOAP_TYPE__ns1__get_USCOREhbgsResponse_get_USCOREhbgsResult (36)
/* ns1:get_hbgsResponse-get_hbgsResult */
struct _ns1__get_USCOREhbgsResponse_get_USCOREhbgsResult
{
	struct soap_dom_element __any;	/* external */
	struct soap_dom_element __mixed;	/* external */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREhbgsResponse
#define SOAP_TYPE__ns1__get_USCOREhbgsResponse (35)
/* ns1:get_hbgsResponse */
struct _ns1__get_USCOREhbgsResponse
{
	struct _ns1__get_USCOREhbgsResponse_get_USCOREhbgsResult *get_USCOREhbgsResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:get_hbgsResponse-get_hbgsResult */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREhbwsh
#define SOAP_TYPE__ns1__get_USCOREhbwsh (38)
/* ns1:get_hbwsh */
struct _ns1__get_USCOREhbwsh
{
	char *gs;	/* optional element of type xsd:string */
	char *id;	/* optional element of type xsd:string */
	char *yyzd;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREhbwshResponse_get_USCOREhbwshResult
#define SOAP_TYPE__ns1__get_USCOREhbwshResponse_get_USCOREhbwshResult (40)
/* ns1:get_hbwshResponse-get_hbwshResult */
struct _ns1__get_USCOREhbwshResponse_get_USCOREhbwshResult
{
	struct soap_dom_element __any;	/* external */
	struct soap_dom_element __mixed;	/* external */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREhbwshResponse
#define SOAP_TYPE__ns1__get_USCOREhbwshResponse (39)
/* ns1:get_hbwshResponse */
struct _ns1__get_USCOREhbwshResponse
{
	struct _ns1__get_USCOREhbwshResponse_get_USCOREhbwshResult *get_USCOREhbwshResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:get_hbwshResponse-get_hbwshResult */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREmx
#define SOAP_TYPE__ns1__get_USCOREmx (42)
/* ns1:get_mx */
struct _ns1__get_USCOREmx
{
	char *gs;	/* optional element of type xsd:string */
	char *id;	/* optional element of type xsd:string */
	char *yyzd;	/* optional element of type xsd:string */
	char *smdate1;	/* optional element of type xsd:string */
	char *smdate2;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREmxResponse_get_USCOREmxResult
#define SOAP_TYPE__ns1__get_USCOREmxResponse_get_USCOREmxResult (44)
/* ns1:get_mxResponse-get_mxResult */
struct _ns1__get_USCOREmxResponse_get_USCOREmxResult
{
	struct soap_dom_element __any;	/* external */
	struct soap_dom_element __mixed;	/* external */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREmxResponse
#define SOAP_TYPE__ns1__get_USCOREmxResponse (43)
/* ns1:get_mxResponse */
struct _ns1__get_USCOREmxResponse
{
	struct _ns1__get_USCOREmxResponse_get_USCOREmxResult *get_USCOREmxResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:get_mxResponse-get_mxResult */
};
#endif

#ifndef SOAP_TYPE__ns1__hbwsh_USCOREupdate
#define SOAP_TYPE__ns1__hbwsh_USCOREupdate (46)
/* ns1:hbwsh_update */
struct _ns1__hbwsh_USCOREupdate
{
	char *id;	/* optional element of type xsd:string */
	char *gs;	/* optional element of type xsd:string */
	char *zje;	/* required element of type xsd:decimal */
	char *optid;	/* optional element of type xsd:string */
	char *fs;	/* optional element of type xsd:string */
	time_t xzrq;	/* required element of type xsd:dateTime */
	char *UserName;	/* optional element of type xsd:string */
	char *Password;	/* optional element of type xsd:string */
	char *yyzd;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__hbwsh_USCOREupdateResponse_hbwsh_USCOREupdateResult
#define SOAP_TYPE__ns1__hbwsh_USCOREupdateResponse_hbwsh_USCOREupdateResult (49)
/* ns1:hbwsh_updateResponse-hbwsh_updateResult */
struct _ns1__hbwsh_USCOREupdateResponse_hbwsh_USCOREupdateResult
{
	struct soap_dom_element __any;	/* external */
	struct soap_dom_element __mixed;	/* external */
};
#endif

#ifndef SOAP_TYPE__ns1__hbwsh_USCOREupdateResponse
#define SOAP_TYPE__ns1__hbwsh_USCOREupdateResponse (48)
/* ns1:hbwsh_updateResponse */
struct _ns1__hbwsh_USCOREupdateResponse
{
	struct _ns1__hbwsh_USCOREupdateResponse_hbwsh_USCOREupdateResult *hbwsh_USCOREupdateResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:hbwsh_updateResponse-hbwsh_updateResult */
};
#endif

#ifndef SOAP_TYPE__ns1__hbtsf_USCOREupdate
#define SOAP_TYPE__ns1__hbtsf_USCOREupdate (51)
/* ns1:hbtsf_update */
struct _ns1__hbtsf_USCOREupdate
{
	char *id;	/* optional element of type xsd:string */
	char *zje;	/* required element of type xsd:decimal */
	char *yyzd;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__hbtsf_USCOREupdateResponse_hbtsf_USCOREupdateResult
#define SOAP_TYPE__ns1__hbtsf_USCOREupdateResponse_hbtsf_USCOREupdateResult (53)
/* ns1:hbtsf_updateResponse-hbtsf_updateResult */
struct _ns1__hbtsf_USCOREupdateResponse_hbtsf_USCOREupdateResult
{
	struct soap_dom_element __any;	/* external */
	struct soap_dom_element __mixed;	/* external */
};
#endif

#ifndef SOAP_TYPE__ns1__hbtsf_USCOREupdateResponse
#define SOAP_TYPE__ns1__hbtsf_USCOREupdateResponse (52)
/* ns1:hbtsf_updateResponse */
struct _ns1__hbtsf_USCOREupdateResponse
{
	struct _ns1__hbtsf_USCOREupdateResponse_hbtsf_USCOREupdateResult *hbtsf_USCOREupdateResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:hbtsf_updateResponse-hbtsf_updateResult */
};
#endif

#ifndef SOAP_TYPE__ns1__TZ_USCOREDay
#define SOAP_TYPE__ns1__TZ_USCOREDay (55)
/* ns1:TZ_Day */
struct _ns1__TZ_USCOREDay
{
	char *smdate;	/* optional element of type xsd:string */
	char *Base64;	/* optional element of type xsd:string */
	char *Base64_USCORESHA1;	/* optional element of type xsd:string */
	char *yyzd;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__TZ_USCOREDayResponse_TZ_USCOREDayResult
#define SOAP_TYPE__ns1__TZ_USCOREDayResponse_TZ_USCOREDayResult (57)
/* ns1:TZ_DayResponse-TZ_DayResult */
struct _ns1__TZ_USCOREDayResponse_TZ_USCOREDayResult
{
	struct soap_dom_element __any;	/* external */
	struct soap_dom_element __mixed;	/* external */
};
#endif

#ifndef SOAP_TYPE__ns1__TZ_USCOREDayResponse
#define SOAP_TYPE__ns1__TZ_USCOREDayResponse (56)
/* ns1:TZ_DayResponse */
struct _ns1__TZ_USCOREDayResponse
{
	struct _ns1__TZ_USCOREDayResponse_TZ_USCOREDayResult *TZ_USCOREDayResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:TZ_DayResponse-TZ_DayResult */
};
#endif

#ifndef SOAP_TYPE__ns1__TZ_USCOREMonth
#define SOAP_TYPE__ns1__TZ_USCOREMonth (59)
/* ns1:TZ_Month */
struct _ns1__TZ_USCOREMonth
{
	char *smdate;	/* optional element of type xsd:string */
	char *Base64;	/* optional element of type xsd:string */
	char *Base64_USCORESHA1;	/* optional element of type xsd:string */
	char *yyzd;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__TZ_USCOREMonthResponse_TZ_USCOREMonthResult
#define SOAP_TYPE__ns1__TZ_USCOREMonthResponse_TZ_USCOREMonthResult (61)
/* ns1:TZ_MonthResponse-TZ_MonthResult */
struct _ns1__TZ_USCOREMonthResponse_TZ_USCOREMonthResult
{
	struct soap_dom_element __any;	/* external */
	struct soap_dom_element __mixed;	/* external */
};
#endif

#ifndef SOAP_TYPE__ns1__TZ_USCOREMonthResponse
#define SOAP_TYPE__ns1__TZ_USCOREMonthResponse (60)
/* ns1:TZ_MonthResponse */
struct _ns1__TZ_USCOREMonthResponse
{
	struct _ns1__TZ_USCOREMonthResponse_TZ_USCOREMonthResult *TZ_USCOREMonthResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:TZ_MonthResponse-TZ_MonthResult */
};
#endif

#ifndef SOAP_TYPE__ns1__m_USCOREtz_USCOREupdate
#define SOAP_TYPE__ns1__m_USCOREtz_USCOREupdate (63)
/* ns1:m_tz_update */
struct _ns1__m_USCOREtz_USCOREupdate
{
	char *smdate;	/* optional element of type xsd:string */
	char *filename;	/* optional element of type xsd:string */
	char *yyzd;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__m_USCOREtz_USCOREupdateResponse_m_USCOREtz_USCOREupdateResult
#define SOAP_TYPE__ns1__m_USCOREtz_USCOREupdateResponse_m_USCOREtz_USCOREupdateResult (65)
/* ns1:m_tz_updateResponse-m_tz_updateResult */
struct _ns1__m_USCOREtz_USCOREupdateResponse_m_USCOREtz_USCOREupdateResult
{
	struct soap_dom_element __any;	/* external */
	struct soap_dom_element __mixed;	/* external */
};
#endif

#ifndef SOAP_TYPE__ns1__m_USCOREtz_USCOREupdateResponse
#define SOAP_TYPE__ns1__m_USCOREtz_USCOREupdateResponse (64)
/* ns1:m_tz_updateResponse */
struct _ns1__m_USCOREtz_USCOREupdateResponse
{
	struct _ns1__m_USCOREtz_USCOREupdateResponse_m_USCOREtz_USCOREupdateResult *m_USCOREtz_USCOREupdateResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:m_tz_updateResponse-m_tz_updateResult */
};
#endif

#ifndef SOAP_TYPE__ns1__m_USCOREzb_USCOREtz_USCOREupdate
#define SOAP_TYPE__ns1__m_USCOREzb_USCOREtz_USCOREupdate (67)
/* ns1:m_zb_tz_update */
struct _ns1__m_USCOREzb_USCOREtz_USCOREupdate
{
	char *smdate;	/* optional element of type xsd:string */
	char *filename;	/* optional element of type xsd:string */
	char *yyzd;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__m_USCOREzb_USCOREtz_USCOREupdateResponse_m_USCOREzb_USCOREtz_USCOREupdateResult
#define SOAP_TYPE__ns1__m_USCOREzb_USCOREtz_USCOREupdateResponse_m_USCOREzb_USCOREtz_USCOREupdateResult (69)
/* ns1:m_zb_tz_updateResponse-m_zb_tz_updateResult */
struct _ns1__m_USCOREzb_USCOREtz_USCOREupdateResponse_m_USCOREzb_USCOREtz_USCOREupdateResult
{
	struct soap_dom_element __any;	/* external */
	struct soap_dom_element __mixed;	/* external */
};
#endif

#ifndef SOAP_TYPE__ns1__m_USCOREzb_USCOREtz_USCOREupdateResponse
#define SOAP_TYPE__ns1__m_USCOREzb_USCOREtz_USCOREupdateResponse (68)
/* ns1:m_zb_tz_updateResponse */
struct _ns1__m_USCOREzb_USCOREtz_USCOREupdateResponse
{
	struct _ns1__m_USCOREzb_USCOREtz_USCOREupdateResponse_m_USCOREzb_USCOREtz_USCOREupdateResult *m_USCOREzb_USCOREtz_USCOREupdateResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:m_zb_tz_updateResponse-m_zb_tz_updateResult */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREhbfp
#define SOAP_TYPE__ns1__get_USCOREhbfp (71)
/* ns1:get_hbfp */
struct _ns1__get_USCOREhbfp
{
	char *gs;	/* optional element of type xsd:string */
	char *id;	/* optional element of type xsd:string */
	char *yyzd;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREhbfpResponse_get_USCOREhbfpResult
#define SOAP_TYPE__ns1__get_USCOREhbfpResponse_get_USCOREhbfpResult (73)
/* ns1:get_hbfpResponse-get_hbfpResult */
struct _ns1__get_USCOREhbfpResponse_get_USCOREhbfpResult
{
	struct soap_dom_element __any;	/* external */
	struct soap_dom_element __mixed;	/* external */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREhbfpResponse
#define SOAP_TYPE__ns1__get_USCOREhbfpResponse (72)
/* ns1:get_hbfpResponse */
struct _ns1__get_USCOREhbfpResponse
{
	struct _ns1__get_USCOREhbfpResponse_get_USCOREhbfpResult *get_USCOREhbfpResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:get_hbfpResponse-get_hbfpResult */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREyyzd
#define SOAP_TYPE__ns1__get_USCOREyyzd (75)
/* ns1:get_yyzd */
struct _ns1__get_USCOREyyzd
{
	char *gs;	/* optional element of type xsd:string */
	char *id;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREyyzdResponse_get_USCOREyyzdResult
#define SOAP_TYPE__ns1__get_USCOREyyzdResponse_get_USCOREyyzdResult (77)
/* ns1:get_yyzdResponse-get_yyzdResult */
struct _ns1__get_USCOREyyzdResponse_get_USCOREyyzdResult
{
	struct soap_dom_element __any;	/* external */
	struct soap_dom_element __mixed;	/* external */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREyyzdResponse
#define SOAP_TYPE__ns1__get_USCOREyyzdResponse (76)
/* ns1:get_yyzdResponse */
struct _ns1__get_USCOREyyzdResponse
{
	struct _ns1__get_USCOREyyzdResponse_get_USCOREyyzdResult *get_USCOREyyzdResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:get_yyzdResponse-get_yyzdResult */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREhbwsh_USCOREyue
#define SOAP_TYPE__ns1__get_USCOREhbwsh_USCOREyue (79)
/* ns1:get_hbwsh_yue */
struct _ns1__get_USCOREhbwsh_USCOREyue
{
	char *gs;	/* optional element of type xsd:string */
	char *id;	/* optional element of type xsd:string */
	char *yyzd;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREhbwsh_USCOREyueResponse_get_USCOREhbwsh_USCOREyueResult
#define SOAP_TYPE__ns1__get_USCOREhbwsh_USCOREyueResponse_get_USCOREhbwsh_USCOREyueResult (81)
/* ns1:get_hbwsh_yueResponse-get_hbwsh_yueResult */
struct _ns1__get_USCOREhbwsh_USCOREyueResponse_get_USCOREhbwsh_USCOREyueResult
{
	struct soap_dom_element __any;	/* external */
	struct soap_dom_element __mixed;	/* external */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREhbwsh_USCOREyueResponse
#define SOAP_TYPE__ns1__get_USCOREhbwsh_USCOREyueResponse (80)
/* ns1:get_hbwsh_yueResponse */
struct _ns1__get_USCOREhbwsh_USCOREyueResponse
{
	struct _ns1__get_USCOREhbwsh_USCOREyueResponse_get_USCOREhbwsh_USCOREyueResult *get_USCOREhbwsh_USCOREyueResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:get_hbwsh_yueResponse-get_hbwsh_yueResult */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREyue
#define SOAP_TYPE__ns1__get_USCOREyue (83)
/* ns1:get_yue */
struct _ns1__get_USCOREyue
{
	char *gs;	/* optional element of type xsd:string */
	char *id;	/* optional element of type xsd:string */
	char *yyzd;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREyueResponse_get_USCOREyueResult
#define SOAP_TYPE__ns1__get_USCOREyueResponse_get_USCOREyueResult (85)
/* ns1:get_yueResponse-get_yueResult */
struct _ns1__get_USCOREyueResponse_get_USCOREyueResult
{
	struct soap_dom_element __any;	/* external */
	struct soap_dom_element __mixed;	/* external */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREyueResponse
#define SOAP_TYPE__ns1__get_USCOREyueResponse (84)
/* ns1:get_yueResponse */
struct _ns1__get_USCOREyueResponse
{
	struct _ns1__get_USCOREyueResponse_get_USCOREyueResult *get_USCOREyueResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:get_yueResponse-get_yueResult */
};
#endif

#ifndef SOAP_TYPE__ns1__hbwsh_USCOREyue_USCOREupdate
#define SOAP_TYPE__ns1__hbwsh_USCOREyue_USCOREupdate (87)
/* ns1:hbwsh_yue_update */
struct _ns1__hbwsh_USCOREyue_USCOREupdate
{
	char *id;	/* optional element of type xsd:string */
	char *gs;	/* optional element of type xsd:string */
	char *zje;	/* required element of type xsd:decimal */
	char *optid;	/* optional element of type xsd:string */
	char *fs;	/* optional element of type xsd:string */
	time_t xzrq;	/* required element of type xsd:dateTime */
	char *UserName;	/* optional element of type xsd:string */
	char *Password;	/* optional element of type xsd:string */
	char *yyzd;	/* optional element of type xsd:string */
	char *dzid;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__hbwsh_USCOREyue_USCOREupdateResponse_hbwsh_USCOREyue_USCOREupdateResult
#define SOAP_TYPE__ns1__hbwsh_USCOREyue_USCOREupdateResponse_hbwsh_USCOREyue_USCOREupdateResult (89)
/* ns1:hbwsh_yue_updateResponse-hbwsh_yue_updateResult */
struct _ns1__hbwsh_USCOREyue_USCOREupdateResponse_hbwsh_USCOREyue_USCOREupdateResult
{
	struct soap_dom_element __any;	/* external */
	struct soap_dom_element __mixed;	/* external */
};
#endif

#ifndef SOAP_TYPE__ns1__hbwsh_USCOREyue_USCOREupdateResponse
#define SOAP_TYPE__ns1__hbwsh_USCOREyue_USCOREupdateResponse (88)
/* ns1:hbwsh_yue_updateResponse */
struct _ns1__hbwsh_USCOREyue_USCOREupdateResponse
{
	struct _ns1__hbwsh_USCOREyue_USCOREupdateResponse_hbwsh_USCOREyue_USCOREupdateResult *hbwsh_USCOREyue_USCOREupdateResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:hbwsh_yue_updateResponse-hbwsh_yue_updateResult */
};
#endif

#ifndef SOAP_TYPE__ns1__hbtsf_USCOREyue_USCOREupdate
#define SOAP_TYPE__ns1__hbtsf_USCOREyue_USCOREupdate (91)
/* ns1:hbtsf_yue_update */
struct _ns1__hbtsf_USCOREyue_USCOREupdate
{
	char *id;	/* optional element of type xsd:string */
	char *zje;	/* required element of type xsd:decimal */
	char *yyzd;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__hbtsf_USCOREyue_USCOREupdateResponse_hbtsf_USCOREyue_USCOREupdateResult
#define SOAP_TYPE__ns1__hbtsf_USCOREyue_USCOREupdateResponse_hbtsf_USCOREyue_USCOREupdateResult (93)
/* ns1:hbtsf_yue_updateResponse-hbtsf_yue_updateResult */
struct _ns1__hbtsf_USCOREyue_USCOREupdateResponse_hbtsf_USCOREyue_USCOREupdateResult
{
	struct soap_dom_element __any;	/* external */
	struct soap_dom_element __mixed;	/* external */
};
#endif

#ifndef SOAP_TYPE__ns1__hbtsf_USCOREyue_USCOREupdateResponse
#define SOAP_TYPE__ns1__hbtsf_USCOREyue_USCOREupdateResponse (92)
/* ns1:hbtsf_yue_updateResponse */
struct _ns1__hbtsf_USCOREyue_USCOREupdateResponse
{
	struct _ns1__hbtsf_USCOREyue_USCOREupdateResponse_hbtsf_USCOREyue_USCOREupdateResult *hbtsf_USCOREyue_USCOREupdateResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:hbtsf_yue_updateResponse-hbtsf_yue_updateResult */
};
#endif

#ifndef SOAP_TYPE__ns1__hb_USCOREfp_USCOREdy_USCOREend
#define SOAP_TYPE__ns1__hb_USCOREfp_USCOREdy_USCOREend (95)
/* ns1:hb_fp_dy_end */
struct _ns1__hb_USCOREfp_USCOREdy_USCOREend
{
	char *id;	/* optional element of type xsd:string */
	char *gs;	/* optional element of type xsd:string */
	char *yyzd;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__hb_USCOREfp_USCOREdy_USCOREendResponse_hb_USCOREfp_USCOREdy_USCOREendResult
#define SOAP_TYPE__ns1__hb_USCOREfp_USCOREdy_USCOREendResponse_hb_USCOREfp_USCOREdy_USCOREendResult (97)
/* ns1:hb_fp_dy_endResponse-hb_fp_dy_endResult */
struct _ns1__hb_USCOREfp_USCOREdy_USCOREendResponse_hb_USCOREfp_USCOREdy_USCOREendResult
{
	struct soap_dom_element __any;	/* external */
	struct soap_dom_element __mixed;	/* external */
};
#endif

#ifndef SOAP_TYPE__ns1__hb_USCOREfp_USCOREdy_USCOREendResponse
#define SOAP_TYPE__ns1__hb_USCOREfp_USCOREdy_USCOREendResponse (96)
/* ns1:hb_fp_dy_endResponse */
struct _ns1__hb_USCOREfp_USCOREdy_USCOREendResponse
{
	struct _ns1__hb_USCOREfp_USCOREdy_USCOREendResponse_hb_USCOREfp_USCOREdy_USCOREendResult *hb_USCOREfp_USCOREdy_USCOREendResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:hb_fp_dy_endResponse-hb_fp_dy_endResult */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREwsh
#define SOAP_TYPE__ns1__get_USCOREwsh (99)
/* ns1:get_wsh */
struct _ns1__get_USCOREwsh
{
	char *gs;	/* optional element of type xsd:string */
	char *id;	/* optional element of type xsd:string */
	char *yyzd;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREwshResponse_get_USCOREwshResult
#define SOAP_TYPE__ns1__get_USCOREwshResponse_get_USCOREwshResult (101)
/* ns1:get_wshResponse-get_wshResult */
struct _ns1__get_USCOREwshResponse_get_USCOREwshResult
{
	struct soap_dom_element __any;	/* external */
	struct soap_dom_element __mixed;	/* external */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREwshResponse
#define SOAP_TYPE__ns1__get_USCOREwshResponse (100)
/* ns1:get_wshResponse */
struct _ns1__get_USCOREwshResponse
{
	struct _ns1__get_USCOREwshResponse_get_USCOREwshResult *get_USCOREwshResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:get_wshResponse-get_wshResult */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREzb_USCOREmx
#define SOAP_TYPE__ns1__get_USCOREzb_USCOREmx (103)
/* ns1:get_zb_mx */
struct _ns1__get_USCOREzb_USCOREmx
{
	char *gs;	/* optional element of type xsd:string */
	char *id;	/* optional element of type xsd:string */
	char *yyzd;	/* optional element of type xsd:string */
	char *smdate1;	/* optional element of type xsd:string */
	char *smdate2;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREzb_USCOREmxResponse_get_USCOREzb_USCOREmxResult
#define SOAP_TYPE__ns1__get_USCOREzb_USCOREmxResponse_get_USCOREzb_USCOREmxResult (105)
/* ns1:get_zb_mxResponse-get_zb_mxResult */
struct _ns1__get_USCOREzb_USCOREmxResponse_get_USCOREzb_USCOREmxResult
{
	struct soap_dom_element __any;	/* external */
	struct soap_dom_element __mixed;	/* external */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREzb_USCOREmxResponse
#define SOAP_TYPE__ns1__get_USCOREzb_USCOREmxResponse (104)
/* ns1:get_zb_mxResponse */
struct _ns1__get_USCOREzb_USCOREmxResponse
{
	struct _ns1__get_USCOREzb_USCOREmxResponse_get_USCOREzb_USCOREmxResult *get_USCOREzb_USCOREmxResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:get_zb_mxResponse-get_zb_mxResult */
};
#endif

#ifndef SOAP_TYPE__ns1__wsh_USCOREupdate
#define SOAP_TYPE__ns1__wsh_USCOREupdate (107)
/* ns1:wsh_update */
struct _ns1__wsh_USCOREupdate
{
	char *id;	/* optional element of type xsd:string */
	char *gs;	/* optional element of type xsd:string */
	char *zje;	/* required element of type xsd:decimal */
	char *optid;	/* optional element of type xsd:string */
	char *fs;	/* optional element of type xsd:string */
	time_t xzrq;	/* required element of type xsd:dateTime */
	char *UserName;	/* optional element of type xsd:string */
	char *Password;	/* optional element of type xsd:string */
	char *yyzd;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__wsh_USCOREupdateResponse_wsh_USCOREupdateResult
#define SOAP_TYPE__ns1__wsh_USCOREupdateResponse_wsh_USCOREupdateResult (109)
/* ns1:wsh_updateResponse-wsh_updateResult */
struct _ns1__wsh_USCOREupdateResponse_wsh_USCOREupdateResult
{
	struct soap_dom_element __any;	/* external */
	struct soap_dom_element __mixed;	/* external */
};
#endif

#ifndef SOAP_TYPE__ns1__wsh_USCOREupdateResponse
#define SOAP_TYPE__ns1__wsh_USCOREupdateResponse (108)
/* ns1:wsh_updateResponse */
struct _ns1__wsh_USCOREupdateResponse
{
	struct _ns1__wsh_USCOREupdateResponse_wsh_USCOREupdateResult *wsh_USCOREupdateResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:wsh_updateResponse-wsh_updateResult */
};
#endif

#ifndef SOAP_TYPE__ns1__tsf_USCOREupdate
#define SOAP_TYPE__ns1__tsf_USCOREupdate (111)
/* ns1:tsf_update */
struct _ns1__tsf_USCOREupdate
{
	char *id;	/* optional element of type xsd:string */
	char *zje;	/* required element of type xsd:decimal */
	char *yyzd;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__tsf_USCOREupdateResponse_tsf_USCOREupdateResult
#define SOAP_TYPE__ns1__tsf_USCOREupdateResponse_tsf_USCOREupdateResult (113)
/* ns1:tsf_updateResponse-tsf_updateResult */
struct _ns1__tsf_USCOREupdateResponse_tsf_USCOREupdateResult
{
	struct soap_dom_element __any;	/* external */
	struct soap_dom_element __mixed;	/* external */
};
#endif

#ifndef SOAP_TYPE__ns1__tsf_USCOREupdateResponse
#define SOAP_TYPE__ns1__tsf_USCOREupdateResponse (112)
/* ns1:tsf_updateResponse */
struct _ns1__tsf_USCOREupdateResponse
{
	struct _ns1__tsf_USCOREupdateResponse_tsf_USCOREupdateResult *tsf_USCOREupdateResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:tsf_updateResponse-tsf_updateResult */
};
#endif

#ifndef SOAP_TYPE__ns1__ZB_USCORETZ_USCOREDay
#define SOAP_TYPE__ns1__ZB_USCORETZ_USCOREDay (115)
/* ns1:ZB_TZ_Day */
struct _ns1__ZB_USCORETZ_USCOREDay
{
	char *smdate;	/* optional element of type xsd:string */
	char *Base64;	/* optional element of type xsd:string */
	char *Base64_USCORESHA1;	/* optional element of type xsd:string */
	char *yyzd;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__ZB_USCORETZ_USCOREDayResponse_ZB_USCORETZ_USCOREDayResult
#define SOAP_TYPE__ns1__ZB_USCORETZ_USCOREDayResponse_ZB_USCORETZ_USCOREDayResult (117)
/* ns1:ZB_TZ_DayResponse-ZB_TZ_DayResult */
struct _ns1__ZB_USCORETZ_USCOREDayResponse_ZB_USCORETZ_USCOREDayResult
{
	struct soap_dom_element __any;	/* external */
	struct soap_dom_element __mixed;	/* external */
};
#endif

#ifndef SOAP_TYPE__ns1__ZB_USCORETZ_USCOREDayResponse
#define SOAP_TYPE__ns1__ZB_USCORETZ_USCOREDayResponse (116)
/* ns1:ZB_TZ_DayResponse */
struct _ns1__ZB_USCORETZ_USCOREDayResponse
{
	struct _ns1__ZB_USCORETZ_USCOREDayResponse_ZB_USCORETZ_USCOREDayResult *ZB_USCORETZ_USCOREDayResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:ZB_TZ_DayResponse-ZB_TZ_DayResult */
};
#endif

#ifndef SOAP_TYPE__ns1__ZB_USCORETZ_USCOREMonth
#define SOAP_TYPE__ns1__ZB_USCORETZ_USCOREMonth (119)
/* ns1:ZB_TZ_Month */
struct _ns1__ZB_USCORETZ_USCOREMonth
{
	char *smdate;	/* optional element of type xsd:string */
	char *Base64;	/* optional element of type xsd:string */
	char *Base64_USCORESHA1;	/* optional element of type xsd:string */
	char *yyzd;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__ZB_USCORETZ_USCOREMonthResponse_ZB_USCORETZ_USCOREMonthResult
#define SOAP_TYPE__ns1__ZB_USCORETZ_USCOREMonthResponse_ZB_USCORETZ_USCOREMonthResult (121)
/* ns1:ZB_TZ_MonthResponse-ZB_TZ_MonthResult */
struct _ns1__ZB_USCORETZ_USCOREMonthResponse_ZB_USCORETZ_USCOREMonthResult
{
	struct soap_dom_element __any;	/* external */
	struct soap_dom_element __mixed;	/* external */
};
#endif

#ifndef SOAP_TYPE__ns1__ZB_USCORETZ_USCOREMonthResponse
#define SOAP_TYPE__ns1__ZB_USCORETZ_USCOREMonthResponse (120)
/* ns1:ZB_TZ_MonthResponse */
struct _ns1__ZB_USCORETZ_USCOREMonthResponse
{
	struct _ns1__ZB_USCORETZ_USCOREMonthResponse_ZB_USCORETZ_USCOREMonthResult *ZB_USCORETZ_USCOREMonthResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:ZB_TZ_MonthResponse-ZB_TZ_MonthResult */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREzbfp
#define SOAP_TYPE__ns1__get_USCOREzbfp (123)
/* ns1:get_zbfp */
struct _ns1__get_USCOREzbfp
{
	char *gs;	/* optional element of type xsd:string */
	char *id;	/* optional element of type xsd:string */
	char *yyzd;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREzbfpResponse_get_USCOREzbfpResult
#define SOAP_TYPE__ns1__get_USCOREzbfpResponse_get_USCOREzbfpResult (125)
/* ns1:get_zbfpResponse-get_zbfpResult */
struct _ns1__get_USCOREzbfpResponse_get_USCOREzbfpResult
{
	struct soap_dom_element __any;	/* external */
	struct soap_dom_element __mixed;	/* external */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREzbfpResponse
#define SOAP_TYPE__ns1__get_USCOREzbfpResponse (124)
/* ns1:get_zbfpResponse */
struct _ns1__get_USCOREzbfpResponse
{
	struct _ns1__get_USCOREzbfpResponse_get_USCOREzbfpResult *get_USCOREzbfpResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:get_zbfpResponse-get_zbfpResult */
};
#endif

#ifndef SOAP_TYPE__ns1__fp_USCOREdy_USCOREend
#define SOAP_TYPE__ns1__fp_USCOREdy_USCOREend (127)
/* ns1:fp_dy_end */
struct _ns1__fp_USCOREdy_USCOREend
{
	char *id;	/* optional element of type xsd:string */
	char *gs;	/* optional element of type xsd:string */
	char *yyzd;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__fp_USCOREdy_USCOREendResponse_fp_USCOREdy_USCOREendResult
#define SOAP_TYPE__ns1__fp_USCOREdy_USCOREendResponse_fp_USCOREdy_USCOREendResult (129)
/* ns1:fp_dy_endResponse-fp_dy_endResult */
struct _ns1__fp_USCOREdy_USCOREendResponse_fp_USCOREdy_USCOREendResult
{
	struct soap_dom_element __any;	/* external */
	struct soap_dom_element __mixed;	/* external */
};
#endif

#ifndef SOAP_TYPE__ns1__fp_USCOREdy_USCOREendResponse
#define SOAP_TYPE__ns1__fp_USCOREdy_USCOREendResponse (128)
/* ns1:fp_dy_endResponse */
struct _ns1__fp_USCOREdy_USCOREendResponse
{
	struct _ns1__fp_USCOREdy_USCOREendResponse_fp_USCOREdy_USCOREendResult *fp_USCOREdy_USCOREendResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:fp_dy_endResponse-fp_dy_endResult */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREhbgs1
#define SOAP_TYPE__ns1__get_USCOREhbgs1 (131)
/* ns1:get_hbgs1 */
struct _ns1__get_USCOREhbgs1
{
	char *str;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREhbgs1Response_get_USCOREhbgs1Result
#define SOAP_TYPE__ns1__get_USCOREhbgs1Response_get_USCOREhbgs1Result (133)
/* ns1:get_hbgs1Response-get_hbgs1Result */
struct _ns1__get_USCOREhbgs1Response_get_USCOREhbgs1Result
{
	struct soap_dom_element __any;	/* external */
	struct soap_dom_element __mixed;	/* external */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREhbgs1Response
#define SOAP_TYPE__ns1__get_USCOREhbgs1Response (132)
/* ns1:get_hbgs1Response */
struct _ns1__get_USCOREhbgs1Response
{
	struct _ns1__get_USCOREhbgs1Response_get_USCOREhbgs1Result *get_USCOREhbgs1Result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:get_hbgs1Response-get_hbgs1Result */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREhbwsh1
#define SOAP_TYPE__ns1__get_USCOREhbwsh1 (135)
/* ns1:get_hbwsh1 */
struct _ns1__get_USCOREhbwsh1
{
	char *gs;	/* optional element of type xsd:string */
	char *id;	/* optional element of type xsd:string */
	char *yyzd;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREhbwsh1Response_get_USCOREhbwsh1Result
#define SOAP_TYPE__ns1__get_USCOREhbwsh1Response_get_USCOREhbwsh1Result (137)
/* ns1:get_hbwsh1Response-get_hbwsh1Result */
struct _ns1__get_USCOREhbwsh1Response_get_USCOREhbwsh1Result
{
	struct soap_dom_element __any;	/* external */
	struct soap_dom_element __mixed;	/* external */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREhbwsh1Response
#define SOAP_TYPE__ns1__get_USCOREhbwsh1Response (136)
/* ns1:get_hbwsh1Response */
struct _ns1__get_USCOREhbwsh1Response
{
	struct _ns1__get_USCOREhbwsh1Response_get_USCOREhbwsh1Result *get_USCOREhbwsh1Result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:get_hbwsh1Response-get_hbwsh1Result */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREmx1
#define SOAP_TYPE__ns1__get_USCOREmx1 (139)
/* ns1:get_mx1 */
struct _ns1__get_USCOREmx1
{
	char *gs;	/* optional element of type xsd:string */
	char *id;	/* optional element of type xsd:string */
	char *yyzd;	/* optional element of type xsd:string */
	char *smdate1;	/* optional element of type xsd:string */
	char *smdate2;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREmx1Response_get_USCOREmx1Result
#define SOAP_TYPE__ns1__get_USCOREmx1Response_get_USCOREmx1Result (141)
/* ns1:get_mx1Response-get_mx1Result */
struct _ns1__get_USCOREmx1Response_get_USCOREmx1Result
{
	struct soap_dom_element __any;	/* external */
	struct soap_dom_element __mixed;	/* external */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREmx1Response
#define SOAP_TYPE__ns1__get_USCOREmx1Response (140)
/* ns1:get_mx1Response */
struct _ns1__get_USCOREmx1Response
{
	struct _ns1__get_USCOREmx1Response_get_USCOREmx1Result *get_USCOREmx1Result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:get_mx1Response-get_mx1Result */
};
#endif

#ifndef SOAP_TYPE__ns1__hbwsh_USCOREupdate1
#define SOAP_TYPE__ns1__hbwsh_USCOREupdate1 (143)
/* ns1:hbwsh_update1 */
struct _ns1__hbwsh_USCOREupdate1
{
	char *id;	/* optional element of type xsd:string */
	char *gs;	/* optional element of type xsd:string */
	char *zje;	/* required element of type xsd:decimal */
	char *optid;	/* optional element of type xsd:string */
	char *fs;	/* optional element of type xsd:string */
	time_t xzrq;	/* required element of type xsd:dateTime */
	char *UserName;	/* optional element of type xsd:string */
	char *Password;	/* optional element of type xsd:string */
	char *yyzd;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__hbwsh_USCOREupdate1Response_hbwsh_USCOREupdate1Result
#define SOAP_TYPE__ns1__hbwsh_USCOREupdate1Response_hbwsh_USCOREupdate1Result (145)
/* ns1:hbwsh_update1Response-hbwsh_update1Result */
struct _ns1__hbwsh_USCOREupdate1Response_hbwsh_USCOREupdate1Result
{
	struct soap_dom_element __any;	/* external */
	struct soap_dom_element __mixed;	/* external */
};
#endif

#ifndef SOAP_TYPE__ns1__hbwsh_USCOREupdate1Response
#define SOAP_TYPE__ns1__hbwsh_USCOREupdate1Response (144)
/* ns1:hbwsh_update1Response */
struct _ns1__hbwsh_USCOREupdate1Response
{
	struct _ns1__hbwsh_USCOREupdate1Response_hbwsh_USCOREupdate1Result *hbwsh_USCOREupdate1Result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:hbwsh_update1Response-hbwsh_update1Result */
};
#endif

#ifndef SOAP_TYPE__ns1__hbtsf_USCOREupdate1
#define SOAP_TYPE__ns1__hbtsf_USCOREupdate1 (147)
/* ns1:hbtsf_update1 */
struct _ns1__hbtsf_USCOREupdate1
{
	char *id;	/* optional element of type xsd:string */
	char *zje;	/* required element of type xsd:decimal */
	char *yyzd;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__hbtsf_USCOREupdate1Response_hbtsf_USCOREupdate1Result
#define SOAP_TYPE__ns1__hbtsf_USCOREupdate1Response_hbtsf_USCOREupdate1Result (149)
/* ns1:hbtsf_update1Response-hbtsf_update1Result */
struct _ns1__hbtsf_USCOREupdate1Response_hbtsf_USCOREupdate1Result
{
	struct soap_dom_element __any;	/* external */
	struct soap_dom_element __mixed;	/* external */
};
#endif

#ifndef SOAP_TYPE__ns1__hbtsf_USCOREupdate1Response
#define SOAP_TYPE__ns1__hbtsf_USCOREupdate1Response (148)
/* ns1:hbtsf_update1Response */
struct _ns1__hbtsf_USCOREupdate1Response
{
	struct _ns1__hbtsf_USCOREupdate1Response_hbtsf_USCOREupdate1Result *hbtsf_USCOREupdate1Result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:hbtsf_update1Response-hbtsf_update1Result */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREhbfp1
#define SOAP_TYPE__ns1__get_USCOREhbfp1 (151)
/* ns1:get_hbfp1 */
struct _ns1__get_USCOREhbfp1
{
	char *gs;	/* optional element of type xsd:string */
	char *id;	/* optional element of type xsd:string */
	char *yyzd;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREhbfp1Response_get_USCOREhbfp1Result
#define SOAP_TYPE__ns1__get_USCOREhbfp1Response_get_USCOREhbfp1Result (153)
/* ns1:get_hbfp1Response-get_hbfp1Result */
struct _ns1__get_USCOREhbfp1Response_get_USCOREhbfp1Result
{
	struct soap_dom_element __any;	/* external */
	struct soap_dom_element __mixed;	/* external */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREhbfp1Response
#define SOAP_TYPE__ns1__get_USCOREhbfp1Response (152)
/* ns1:get_hbfp1Response */
struct _ns1__get_USCOREhbfp1Response
{
	struct _ns1__get_USCOREhbfp1Response_get_USCOREhbfp1Result *get_USCOREhbfp1Result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:get_hbfp1Response-get_hbfp1Result */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREyyzd1
#define SOAP_TYPE__ns1__get_USCOREyyzd1 (155)
/* ns1:get_yyzd1 */
struct _ns1__get_USCOREyyzd1
{
	char *gs;	/* optional element of type xsd:string */
	char *id;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREyyzd1Response_get_USCOREyyzd1Result
#define SOAP_TYPE__ns1__get_USCOREyyzd1Response_get_USCOREyyzd1Result (157)
/* ns1:get_yyzd1Response-get_yyzd1Result */
struct _ns1__get_USCOREyyzd1Response_get_USCOREyyzd1Result
{
	struct soap_dom_element __any;	/* external */
	struct soap_dom_element __mixed;	/* external */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREyyzd1Response
#define SOAP_TYPE__ns1__get_USCOREyyzd1Response (156)
/* ns1:get_yyzd1Response */
struct _ns1__get_USCOREyyzd1Response
{
	struct _ns1__get_USCOREyyzd1Response_get_USCOREyyzd1Result *get_USCOREyyzd1Result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:get_yyzd1Response-get_yyzd1Result */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREyue1
#define SOAP_TYPE__ns1__get_USCOREyue1 (159)
/* ns1:get_yue1 */
struct _ns1__get_USCOREyue1
{
	char *gs;	/* optional element of type xsd:string */
	char *id;	/* optional element of type xsd:string */
	char *yyzd;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREyue1Response_get_USCOREyue1Result
#define SOAP_TYPE__ns1__get_USCOREyue1Response_get_USCOREyue1Result (161)
/* ns1:get_yue1Response-get_yue1Result */
struct _ns1__get_USCOREyue1Response_get_USCOREyue1Result
{
	struct soap_dom_element __any;	/* external */
	struct soap_dom_element __mixed;	/* external */
};
#endif

#ifndef SOAP_TYPE__ns1__get_USCOREyue1Response
#define SOAP_TYPE__ns1__get_USCOREyue1Response (160)
/* ns1:get_yue1Response */
struct _ns1__get_USCOREyue1Response
{
	struct _ns1__get_USCOREyue1Response_get_USCOREyue1Result *get_USCOREyue1Result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:get_yue1Response-get_yue1Result */
};
#endif

#ifndef SOAP_TYPE__ns1__hb_USCOREfp_USCOREdy_USCOREend1
#define SOAP_TYPE__ns1__hb_USCOREfp_USCOREdy_USCOREend1 (163)
/* ns1:hb_fp_dy_end1 */
struct _ns1__hb_USCOREfp_USCOREdy_USCOREend1
{
	char *id;	/* optional element of type xsd:string */
	char *gs;	/* optional element of type xsd:string */
	char *yyzd;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__hb_USCOREfp_USCOREdy_USCOREend1Response_hb_USCOREfp_USCOREdy_USCOREend1Result
#define SOAP_TYPE__ns1__hb_USCOREfp_USCOREdy_USCOREend1Response_hb_USCOREfp_USCOREdy_USCOREend1Result (165)
/* ns1:hb_fp_dy_end1Response-hb_fp_dy_end1Result */
struct _ns1__hb_USCOREfp_USCOREdy_USCOREend1Response_hb_USCOREfp_USCOREdy_USCOREend1Result
{
	struct soap_dom_element __any;	/* external */
	struct soap_dom_element __mixed;	/* external */
};
#endif

#ifndef SOAP_TYPE__ns1__hb_USCOREfp_USCOREdy_USCOREend1Response
#define SOAP_TYPE__ns1__hb_USCOREfp_USCOREdy_USCOREend1Response (164)
/* ns1:hb_fp_dy_end1Response */
struct _ns1__hb_USCOREfp_USCOREdy_USCOREend1Response
{
	struct _ns1__hb_USCOREfp_USCOREdy_USCOREend1Response_hb_USCOREfp_USCOREdy_USCOREend1Result *hb_USCOREfp_USCOREdy_USCOREend1Result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:hb_fp_dy_end1Response-hb_fp_dy_end1Result */
};
#endif

#ifndef SOAP_TYPE__ns1__TZ_USCOREDay1
#define SOAP_TYPE__ns1__TZ_USCOREDay1 (167)
/* ns1:TZ_Day1 */
struct _ns1__TZ_USCOREDay1
{
	char *smdate;	/* optional element of type xsd:string */
	char *Base64;	/* optional element of type xsd:string */
	char *Base64_USCORESHA1;	/* optional element of type xsd:string */
	char *yyzd;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__TZ_USCOREDay1Response_TZ_USCOREDay1Result
#define SOAP_TYPE__ns1__TZ_USCOREDay1Response_TZ_USCOREDay1Result (169)
/* ns1:TZ_Day1Response-TZ_Day1Result */
struct _ns1__TZ_USCOREDay1Response_TZ_USCOREDay1Result
{
	struct soap_dom_element __any;	/* external */
	struct soap_dom_element __mixed;	/* external */
};
#endif

#ifndef SOAP_TYPE__ns1__TZ_USCOREDay1Response
#define SOAP_TYPE__ns1__TZ_USCOREDay1Response (168)
/* ns1:TZ_Day1Response */
struct _ns1__TZ_USCOREDay1Response
{
	struct _ns1__TZ_USCOREDay1Response_TZ_USCOREDay1Result *TZ_USCOREDay1Result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:TZ_Day1Response-TZ_Day1Result */
};
#endif

#ifndef SOAP_TYPE__ns1__m_USCOREtz_USCOREupdate1
#define SOAP_TYPE__ns1__m_USCOREtz_USCOREupdate1 (171)
/* ns1:m_tz_update1 */
struct _ns1__m_USCOREtz_USCOREupdate1
{
	char *smdate;	/* optional element of type xsd:string */
	char *filename;	/* optional element of type xsd:string */
	char *yyzd;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__m_USCOREtz_USCOREupdate1Response_m_USCOREtz_USCOREupdate1Result
#define SOAP_TYPE__ns1__m_USCOREtz_USCOREupdate1Response_m_USCOREtz_USCOREupdate1Result (173)
/* ns1:m_tz_update1Response-m_tz_update1Result */
struct _ns1__m_USCOREtz_USCOREupdate1Response_m_USCOREtz_USCOREupdate1Result
{
	struct soap_dom_element __any;	/* external */
	struct soap_dom_element __mixed;	/* external */
};
#endif

#ifndef SOAP_TYPE__ns1__m_USCOREtz_USCOREupdate1Response
#define SOAP_TYPE__ns1__m_USCOREtz_USCOREupdate1Response (172)
/* ns1:m_tz_update1Response */
struct _ns1__m_USCOREtz_USCOREupdate1Response
{
	struct _ns1__m_USCOREtz_USCOREupdate1Response_m_USCOREtz_USCOREupdate1Result *m_USCOREtz_USCOREupdate1Result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:m_tz_update1Response-m_tz_update1Result */
};
#endif

#ifndef SOAP_TYPE___ns1__GetTime
#define SOAP_TYPE___ns1__GetTime (178)
/* Operation wrapper: */
struct __ns1__GetTime
{
	struct _ns1__GetTime *ns1__GetTime;	/* optional element of type ns1:GetTime */
};
#endif

#ifndef SOAP_TYPE___ns1__GetDNS
#define SOAP_TYPE___ns1__GetDNS (182)
/* Operation wrapper: */
struct __ns1__GetDNS
{
	struct _ns1__GetDNS *ns1__GetDNS;	/* optional element of type ns1:GetDNS */
};
#endif

#ifndef SOAP_TYPE___ns1__GetHostInfo
#define SOAP_TYPE___ns1__GetHostInfo (186)
/* Operation wrapper: */
struct __ns1__GetHostInfo
{
	struct _ns1__GetHostInfo *ns1__GetHostInfo;	/* optional element of type ns1:GetHostInfo */
};
#endif

#ifndef SOAP_TYPE___ns1__CheckSHA1
#define SOAP_TYPE___ns1__CheckSHA1 (190)
/* Operation wrapper: */
struct __ns1__CheckSHA1
{
	struct _ns1__CheckSHA1 *ns1__CheckSHA1;	/* optional element of type ns1:CheckSHA1 */
};
#endif

#ifndef SOAP_TYPE___ns1__ToBASE64
#define SOAP_TYPE___ns1__ToBASE64 (194)
/* Operation wrapper: */
struct __ns1__ToBASE64
{
	struct _ns1__ToBASE64 *ns1__ToBASE64;	/* optional element of type ns1:ToBASE64 */
};
#endif

#ifndef SOAP_TYPE___ns1__FromBASE64
#define SOAP_TYPE___ns1__FromBASE64 (198)
/* Operation wrapper: */
struct __ns1__FromBASE64
{
	struct _ns1__FromBASE64 *ns1__FromBASE64;	/* optional element of type ns1:FromBASE64 */
};
#endif

#ifndef SOAP_TYPE___ns1__get_USCOREhbgs
#define SOAP_TYPE___ns1__get_USCOREhbgs (202)
/* Operation wrapper: */
struct __ns1__get_USCOREhbgs
{
	struct _ns1__get_USCOREhbgs *ns1__get_USCOREhbgs;	/* optional element of type ns1:get_hbgs */
};
#endif

#ifndef SOAP_TYPE___ns1__get_USCOREhbwsh
#define SOAP_TYPE___ns1__get_USCOREhbwsh (206)
/* Operation wrapper: */
struct __ns1__get_USCOREhbwsh
{
	struct _ns1__get_USCOREhbwsh *ns1__get_USCOREhbwsh;	/* optional element of type ns1:get_hbwsh */
};
#endif

#ifndef SOAP_TYPE___ns1__get_USCOREmx
#define SOAP_TYPE___ns1__get_USCOREmx (210)
/* Operation wrapper: */
struct __ns1__get_USCOREmx
{
	struct _ns1__get_USCOREmx *ns1__get_USCOREmx;	/* optional element of type ns1:get_mx */
};
#endif

#ifndef SOAP_TYPE___ns1__hbwsh_USCOREupdate
#define SOAP_TYPE___ns1__hbwsh_USCOREupdate (214)
/* Operation wrapper: */
struct __ns1__hbwsh_USCOREupdate
{
	struct _ns1__hbwsh_USCOREupdate *ns1__hbwsh_USCOREupdate;	/* optional element of type ns1:hbwsh_update */
};
#endif

#ifndef SOAP_TYPE___ns1__hbtsf_USCOREupdate
#define SOAP_TYPE___ns1__hbtsf_USCOREupdate (218)
/* Operation wrapper: */
struct __ns1__hbtsf_USCOREupdate
{
	struct _ns1__hbtsf_USCOREupdate *ns1__hbtsf_USCOREupdate;	/* optional element of type ns1:hbtsf_update */
};
#endif

#ifndef SOAP_TYPE___ns1__TZ_USCOREDay
#define SOAP_TYPE___ns1__TZ_USCOREDay (222)
/* Operation wrapper: */
struct __ns1__TZ_USCOREDay
{
	struct _ns1__TZ_USCOREDay *ns1__TZ_USCOREDay;	/* optional element of type ns1:TZ_Day */
};
#endif

#ifndef SOAP_TYPE___ns1__TZ_USCOREMonth
#define SOAP_TYPE___ns1__TZ_USCOREMonth (226)
/* Operation wrapper: */
struct __ns1__TZ_USCOREMonth
{
	struct _ns1__TZ_USCOREMonth *ns1__TZ_USCOREMonth;	/* optional element of type ns1:TZ_Month */
};
#endif

#ifndef SOAP_TYPE___ns1__m_USCOREtz_USCOREupdate
#define SOAP_TYPE___ns1__m_USCOREtz_USCOREupdate (230)
/* Operation wrapper: */
struct __ns1__m_USCOREtz_USCOREupdate
{
	struct _ns1__m_USCOREtz_USCOREupdate *ns1__m_USCOREtz_USCOREupdate;	/* optional element of type ns1:m_tz_update */
};
#endif

#ifndef SOAP_TYPE___ns1__m_USCOREzb_USCOREtz_USCOREupdate
#define SOAP_TYPE___ns1__m_USCOREzb_USCOREtz_USCOREupdate (234)
/* Operation wrapper: */
struct __ns1__m_USCOREzb_USCOREtz_USCOREupdate
{
	struct _ns1__m_USCOREzb_USCOREtz_USCOREupdate *ns1__m_USCOREzb_USCOREtz_USCOREupdate;	/* optional element of type ns1:m_zb_tz_update */
};
#endif

#ifndef SOAP_TYPE___ns1__get_USCOREhbfp
#define SOAP_TYPE___ns1__get_USCOREhbfp (238)
/* Operation wrapper: */
struct __ns1__get_USCOREhbfp
{
	struct _ns1__get_USCOREhbfp *ns1__get_USCOREhbfp;	/* optional element of type ns1:get_hbfp */
};
#endif

#ifndef SOAP_TYPE___ns1__get_USCOREyyzd
#define SOAP_TYPE___ns1__get_USCOREyyzd (242)
/* Operation wrapper: */
struct __ns1__get_USCOREyyzd
{
	struct _ns1__get_USCOREyyzd *ns1__get_USCOREyyzd;	/* optional element of type ns1:get_yyzd */
};
#endif

#ifndef SOAP_TYPE___ns1__get_USCOREhbwsh_USCOREyue
#define SOAP_TYPE___ns1__get_USCOREhbwsh_USCOREyue (246)
/* Operation wrapper: */
struct __ns1__get_USCOREhbwsh_USCOREyue
{
	struct _ns1__get_USCOREhbwsh_USCOREyue *ns1__get_USCOREhbwsh_USCOREyue;	/* optional element of type ns1:get_hbwsh_yue */
};
#endif

#ifndef SOAP_TYPE___ns1__get_USCOREyue
#define SOAP_TYPE___ns1__get_USCOREyue (250)
/* Operation wrapper: */
struct __ns1__get_USCOREyue
{
	struct _ns1__get_USCOREyue *ns1__get_USCOREyue;	/* optional element of type ns1:get_yue */
};
#endif

#ifndef SOAP_TYPE___ns1__hbwsh_USCOREyue_USCOREupdate
#define SOAP_TYPE___ns1__hbwsh_USCOREyue_USCOREupdate (254)
/* Operation wrapper: */
struct __ns1__hbwsh_USCOREyue_USCOREupdate
{
	struct _ns1__hbwsh_USCOREyue_USCOREupdate *ns1__hbwsh_USCOREyue_USCOREupdate;	/* optional element of type ns1:hbwsh_yue_update */
};
#endif

#ifndef SOAP_TYPE___ns1__hbtsf_USCOREyue_USCOREupdate
#define SOAP_TYPE___ns1__hbtsf_USCOREyue_USCOREupdate (258)
/* Operation wrapper: */
struct __ns1__hbtsf_USCOREyue_USCOREupdate
{
	struct _ns1__hbtsf_USCOREyue_USCOREupdate *ns1__hbtsf_USCOREyue_USCOREupdate;	/* optional element of type ns1:hbtsf_yue_update */
};
#endif

#ifndef SOAP_TYPE___ns1__hb_USCOREfp_USCOREdy_USCOREend
#define SOAP_TYPE___ns1__hb_USCOREfp_USCOREdy_USCOREend (262)
/* Operation wrapper: */
struct __ns1__hb_USCOREfp_USCOREdy_USCOREend
{
	struct _ns1__hb_USCOREfp_USCOREdy_USCOREend *ns1__hb_USCOREfp_USCOREdy_USCOREend;	/* optional element of type ns1:hb_fp_dy_end */
};
#endif

#ifndef SOAP_TYPE___ns1__get_USCOREwsh
#define SOAP_TYPE___ns1__get_USCOREwsh (266)
/* Operation wrapper: */
struct __ns1__get_USCOREwsh
{
	struct _ns1__get_USCOREwsh *ns1__get_USCOREwsh;	/* optional element of type ns1:get_wsh */
};
#endif

#ifndef SOAP_TYPE___ns1__get_USCOREzb_USCOREmx
#define SOAP_TYPE___ns1__get_USCOREzb_USCOREmx (270)
/* Operation wrapper: */
struct __ns1__get_USCOREzb_USCOREmx
{
	struct _ns1__get_USCOREzb_USCOREmx *ns1__get_USCOREzb_USCOREmx;	/* optional element of type ns1:get_zb_mx */
};
#endif

#ifndef SOAP_TYPE___ns1__wsh_USCOREupdate
#define SOAP_TYPE___ns1__wsh_USCOREupdate (274)
/* Operation wrapper: */
struct __ns1__wsh_USCOREupdate
{
	struct _ns1__wsh_USCOREupdate *ns1__wsh_USCOREupdate;	/* optional element of type ns1:wsh_update */
};
#endif

#ifndef SOAP_TYPE___ns1__tsf_USCOREupdate
#define SOAP_TYPE___ns1__tsf_USCOREupdate (278)
/* Operation wrapper: */
struct __ns1__tsf_USCOREupdate
{
	struct _ns1__tsf_USCOREupdate *ns1__tsf_USCOREupdate;	/* optional element of type ns1:tsf_update */
};
#endif

#ifndef SOAP_TYPE___ns1__ZB_USCORETZ_USCOREDay
#define SOAP_TYPE___ns1__ZB_USCORETZ_USCOREDay (282)
/* Operation wrapper: */
struct __ns1__ZB_USCORETZ_USCOREDay
{
	struct _ns1__ZB_USCORETZ_USCOREDay *ns1__ZB_USCORETZ_USCOREDay;	/* optional element of type ns1:ZB_TZ_Day */
};
#endif

#ifndef SOAP_TYPE___ns1__ZB_USCORETZ_USCOREMonth
#define SOAP_TYPE___ns1__ZB_USCORETZ_USCOREMonth (286)
/* Operation wrapper: */
struct __ns1__ZB_USCORETZ_USCOREMonth
{
	struct _ns1__ZB_USCORETZ_USCOREMonth *ns1__ZB_USCORETZ_USCOREMonth;	/* optional element of type ns1:ZB_TZ_Month */
};
#endif

#ifndef SOAP_TYPE___ns1__get_USCOREzbfp
#define SOAP_TYPE___ns1__get_USCOREzbfp (290)
/* Operation wrapper: */
struct __ns1__get_USCOREzbfp
{
	struct _ns1__get_USCOREzbfp *ns1__get_USCOREzbfp;	/* optional element of type ns1:get_zbfp */
};
#endif

#ifndef SOAP_TYPE___ns1__fp_USCOREdy_USCOREend
#define SOAP_TYPE___ns1__fp_USCOREdy_USCOREend (294)
/* Operation wrapper: */
struct __ns1__fp_USCOREdy_USCOREend
{
	struct _ns1__fp_USCOREdy_USCOREend *ns1__fp_USCOREdy_USCOREend;	/* optional element of type ns1:fp_dy_end */
};
#endif

#ifndef SOAP_TYPE___ns1__get_USCOREhbgs1
#define SOAP_TYPE___ns1__get_USCOREhbgs1 (298)
/* Operation wrapper: */
struct __ns1__get_USCOREhbgs1
{
	struct _ns1__get_USCOREhbgs1 *ns1__get_USCOREhbgs1;	/* optional element of type ns1:get_hbgs1 */
};
#endif

#ifndef SOAP_TYPE___ns1__get_USCOREhbwsh1
#define SOAP_TYPE___ns1__get_USCOREhbwsh1 (302)
/* Operation wrapper: */
struct __ns1__get_USCOREhbwsh1
{
	struct _ns1__get_USCOREhbwsh1 *ns1__get_USCOREhbwsh1;	/* optional element of type ns1:get_hbwsh1 */
};
#endif

#ifndef SOAP_TYPE___ns1__get_USCOREmx1
#define SOAP_TYPE___ns1__get_USCOREmx1 (306)
/* Operation wrapper: */
struct __ns1__get_USCOREmx1
{
	struct _ns1__get_USCOREmx1 *ns1__get_USCOREmx1;	/* optional element of type ns1:get_mx1 */
};
#endif

#ifndef SOAP_TYPE___ns1__hbwsh_USCOREupdate1
#define SOAP_TYPE___ns1__hbwsh_USCOREupdate1 (310)
/* Operation wrapper: */
struct __ns1__hbwsh_USCOREupdate1
{
	struct _ns1__hbwsh_USCOREupdate1 *ns1__hbwsh_USCOREupdate1;	/* optional element of type ns1:hbwsh_update1 */
};
#endif

#ifndef SOAP_TYPE___ns1__hbtsf_USCOREupdate1
#define SOAP_TYPE___ns1__hbtsf_USCOREupdate1 (314)
/* Operation wrapper: */
struct __ns1__hbtsf_USCOREupdate1
{
	struct _ns1__hbtsf_USCOREupdate1 *ns1__hbtsf_USCOREupdate1;	/* optional element of type ns1:hbtsf_update1 */
};
#endif

#ifndef SOAP_TYPE___ns1__get_USCOREhbfp1
#define SOAP_TYPE___ns1__get_USCOREhbfp1 (318)
/* Operation wrapper: */
struct __ns1__get_USCOREhbfp1
{
	struct _ns1__get_USCOREhbfp1 *ns1__get_USCOREhbfp1;	/* optional element of type ns1:get_hbfp1 */
};
#endif

#ifndef SOAP_TYPE___ns1__get_USCOREyyzd1
#define SOAP_TYPE___ns1__get_USCOREyyzd1 (322)
/* Operation wrapper: */
struct __ns1__get_USCOREyyzd1
{
	struct _ns1__get_USCOREyyzd1 *ns1__get_USCOREyyzd1;	/* optional element of type ns1:get_yyzd1 */
};
#endif

#ifndef SOAP_TYPE___ns1__get_USCOREyue1
#define SOAP_TYPE___ns1__get_USCOREyue1 (326)
/* Operation wrapper: */
struct __ns1__get_USCOREyue1
{
	struct _ns1__get_USCOREyue1 *ns1__get_USCOREyue1;	/* optional element of type ns1:get_yue1 */
};
#endif

#ifndef SOAP_TYPE___ns1__hb_USCOREfp_USCOREdy_USCOREend1
#define SOAP_TYPE___ns1__hb_USCOREfp_USCOREdy_USCOREend1 (330)
/* Operation wrapper: */
struct __ns1__hb_USCOREfp_USCOREdy_USCOREend1
{
	struct _ns1__hb_USCOREfp_USCOREdy_USCOREend1 *ns1__hb_USCOREfp_USCOREdy_USCOREend1;	/* optional element of type ns1:hb_fp_dy_end1 */
};
#endif

#ifndef SOAP_TYPE___ns1__TZ_USCOREDay1
#define SOAP_TYPE___ns1__TZ_USCOREDay1 (334)
/* Operation wrapper: */
struct __ns1__TZ_USCOREDay1
{
	struct _ns1__TZ_USCOREDay1 *ns1__TZ_USCOREDay1;	/* optional element of type ns1:TZ_Day1 */
};
#endif

#ifndef SOAP_TYPE___ns1__m_USCOREtz_USCOREupdate1
#define SOAP_TYPE___ns1__m_USCOREtz_USCOREupdate1 (338)
/* Operation wrapper: */
struct __ns1__m_USCOREtz_USCOREupdate1
{
	struct _ns1__m_USCOREtz_USCOREupdate1 *ns1__m_USCOREtz_USCOREupdate1;	/* optional element of type ns1:m_tz_update1 */
};
#endif

#ifndef SOAP_TYPE___ns1__GetTime_
#define SOAP_TYPE___ns1__GetTime_ (340)
/* Operation wrapper: */
struct __ns1__GetTime_
{
	struct _ns1__GetTime *ns1__GetTime;	/* optional element of type ns1:GetTime */
};
#endif

#ifndef SOAP_TYPE___ns1__GetDNS_
#define SOAP_TYPE___ns1__GetDNS_ (342)
/* Operation wrapper: */
struct __ns1__GetDNS_
{
	struct _ns1__GetDNS *ns1__GetDNS;	/* optional element of type ns1:GetDNS */
};
#endif

#ifndef SOAP_TYPE___ns1__GetHostInfo_
#define SOAP_TYPE___ns1__GetHostInfo_ (344)
/* Operation wrapper: */
struct __ns1__GetHostInfo_
{
	struct _ns1__GetHostInfo *ns1__GetHostInfo;	/* optional element of type ns1:GetHostInfo */
};
#endif

#ifndef SOAP_TYPE___ns1__CheckSHA1_
#define SOAP_TYPE___ns1__CheckSHA1_ (346)
/* Operation wrapper: */
struct __ns1__CheckSHA1_
{
	struct _ns1__CheckSHA1 *ns1__CheckSHA1;	/* optional element of type ns1:CheckSHA1 */
};
#endif

#ifndef SOAP_TYPE___ns1__ToBASE64_
#define SOAP_TYPE___ns1__ToBASE64_ (348)
/* Operation wrapper: */
struct __ns1__ToBASE64_
{
	struct _ns1__ToBASE64 *ns1__ToBASE64;	/* optional element of type ns1:ToBASE64 */
};
#endif

#ifndef SOAP_TYPE___ns1__FromBASE64_
#define SOAP_TYPE___ns1__FromBASE64_ (350)
/* Operation wrapper: */
struct __ns1__FromBASE64_
{
	struct _ns1__FromBASE64 *ns1__FromBASE64;	/* optional element of type ns1:FromBASE64 */
};
#endif

#ifndef SOAP_TYPE___ns1__get_USCOREhbgs_
#define SOAP_TYPE___ns1__get_USCOREhbgs_ (352)
/* Operation wrapper: */
struct __ns1__get_USCOREhbgs_
{
	struct _ns1__get_USCOREhbgs *ns1__get_USCOREhbgs;	/* optional element of type ns1:get_hbgs */
};
#endif

#ifndef SOAP_TYPE___ns1__get_USCOREhbwsh_
#define SOAP_TYPE___ns1__get_USCOREhbwsh_ (354)
/* Operation wrapper: */
struct __ns1__get_USCOREhbwsh_
{
	struct _ns1__get_USCOREhbwsh *ns1__get_USCOREhbwsh;	/* optional element of type ns1:get_hbwsh */
};
#endif

#ifndef SOAP_TYPE___ns1__get_USCOREmx_
#define SOAP_TYPE___ns1__get_USCOREmx_ (356)
/* Operation wrapper: */
struct __ns1__get_USCOREmx_
{
	struct _ns1__get_USCOREmx *ns1__get_USCOREmx;	/* optional element of type ns1:get_mx */
};
#endif

#ifndef SOAP_TYPE___ns1__hbwsh_USCOREupdate_
#define SOAP_TYPE___ns1__hbwsh_USCOREupdate_ (358)
/* Operation wrapper: */
struct __ns1__hbwsh_USCOREupdate_
{
	struct _ns1__hbwsh_USCOREupdate *ns1__hbwsh_USCOREupdate;	/* optional element of type ns1:hbwsh_update */
};
#endif

#ifndef SOAP_TYPE___ns1__hbtsf_USCOREupdate_
#define SOAP_TYPE___ns1__hbtsf_USCOREupdate_ (360)
/* Operation wrapper: */
struct __ns1__hbtsf_USCOREupdate_
{
	struct _ns1__hbtsf_USCOREupdate *ns1__hbtsf_USCOREupdate;	/* optional element of type ns1:hbtsf_update */
};
#endif

#ifndef SOAP_TYPE___ns1__TZ_USCOREDay_
#define SOAP_TYPE___ns1__TZ_USCOREDay_ (362)
/* Operation wrapper: */
struct __ns1__TZ_USCOREDay_
{
	struct _ns1__TZ_USCOREDay *ns1__TZ_USCOREDay;	/* optional element of type ns1:TZ_Day */
};
#endif

#ifndef SOAP_TYPE___ns1__TZ_USCOREMonth_
#define SOAP_TYPE___ns1__TZ_USCOREMonth_ (364)
/* Operation wrapper: */
struct __ns1__TZ_USCOREMonth_
{
	struct _ns1__TZ_USCOREMonth *ns1__TZ_USCOREMonth;	/* optional element of type ns1:TZ_Month */
};
#endif

#ifndef SOAP_TYPE___ns1__m_USCOREtz_USCOREupdate_
#define SOAP_TYPE___ns1__m_USCOREtz_USCOREupdate_ (366)
/* Operation wrapper: */
struct __ns1__m_USCOREtz_USCOREupdate_
{
	struct _ns1__m_USCOREtz_USCOREupdate *ns1__m_USCOREtz_USCOREupdate;	/* optional element of type ns1:m_tz_update */
};
#endif

#ifndef SOAP_TYPE___ns1__m_USCOREzb_USCOREtz_USCOREupdate_
#define SOAP_TYPE___ns1__m_USCOREzb_USCOREtz_USCOREupdate_ (368)
/* Operation wrapper: */
struct __ns1__m_USCOREzb_USCOREtz_USCOREupdate_
{
	struct _ns1__m_USCOREzb_USCOREtz_USCOREupdate *ns1__m_USCOREzb_USCOREtz_USCOREupdate;	/* optional element of type ns1:m_zb_tz_update */
};
#endif

#ifndef SOAP_TYPE___ns1__get_USCOREhbfp_
#define SOAP_TYPE___ns1__get_USCOREhbfp_ (370)
/* Operation wrapper: */
struct __ns1__get_USCOREhbfp_
{
	struct _ns1__get_USCOREhbfp *ns1__get_USCOREhbfp;	/* optional element of type ns1:get_hbfp */
};
#endif

#ifndef SOAP_TYPE___ns1__get_USCOREyyzd_
#define SOAP_TYPE___ns1__get_USCOREyyzd_ (372)
/* Operation wrapper: */
struct __ns1__get_USCOREyyzd_
{
	struct _ns1__get_USCOREyyzd *ns1__get_USCOREyyzd;	/* optional element of type ns1:get_yyzd */
};
#endif

#ifndef SOAP_TYPE___ns1__get_USCOREhbwsh_USCOREyue_
#define SOAP_TYPE___ns1__get_USCOREhbwsh_USCOREyue_ (374)
/* Operation wrapper: */
struct __ns1__get_USCOREhbwsh_USCOREyue_
{
	struct _ns1__get_USCOREhbwsh_USCOREyue *ns1__get_USCOREhbwsh_USCOREyue;	/* optional element of type ns1:get_hbwsh_yue */
};
#endif

#ifndef SOAP_TYPE___ns1__get_USCOREyue_
#define SOAP_TYPE___ns1__get_USCOREyue_ (376)
/* Operation wrapper: */
struct __ns1__get_USCOREyue_
{
	struct _ns1__get_USCOREyue *ns1__get_USCOREyue;	/* optional element of type ns1:get_yue */
};
#endif

#ifndef SOAP_TYPE___ns1__hbwsh_USCOREyue_USCOREupdate_
#define SOAP_TYPE___ns1__hbwsh_USCOREyue_USCOREupdate_ (378)
/* Operation wrapper: */
struct __ns1__hbwsh_USCOREyue_USCOREupdate_
{
	struct _ns1__hbwsh_USCOREyue_USCOREupdate *ns1__hbwsh_USCOREyue_USCOREupdate;	/* optional element of type ns1:hbwsh_yue_update */
};
#endif

#ifndef SOAP_TYPE___ns1__hbtsf_USCOREyue_USCOREupdate_
#define SOAP_TYPE___ns1__hbtsf_USCOREyue_USCOREupdate_ (380)
/* Operation wrapper: */
struct __ns1__hbtsf_USCOREyue_USCOREupdate_
{
	struct _ns1__hbtsf_USCOREyue_USCOREupdate *ns1__hbtsf_USCOREyue_USCOREupdate;	/* optional element of type ns1:hbtsf_yue_update */
};
#endif

#ifndef SOAP_TYPE___ns1__hb_USCOREfp_USCOREdy_USCOREend_
#define SOAP_TYPE___ns1__hb_USCOREfp_USCOREdy_USCOREend_ (382)
/* Operation wrapper: */
struct __ns1__hb_USCOREfp_USCOREdy_USCOREend_
{
	struct _ns1__hb_USCOREfp_USCOREdy_USCOREend *ns1__hb_USCOREfp_USCOREdy_USCOREend;	/* optional element of type ns1:hb_fp_dy_end */
};
#endif

#ifndef SOAP_TYPE___ns1__get_USCOREwsh_
#define SOAP_TYPE___ns1__get_USCOREwsh_ (384)
/* Operation wrapper: */
struct __ns1__get_USCOREwsh_
{
	struct _ns1__get_USCOREwsh *ns1__get_USCOREwsh;	/* optional element of type ns1:get_wsh */
};
#endif

#ifndef SOAP_TYPE___ns1__get_USCOREzb_USCOREmx_
#define SOAP_TYPE___ns1__get_USCOREzb_USCOREmx_ (386)
/* Operation wrapper: */
struct __ns1__get_USCOREzb_USCOREmx_
{
	struct _ns1__get_USCOREzb_USCOREmx *ns1__get_USCOREzb_USCOREmx;	/* optional element of type ns1:get_zb_mx */
};
#endif

#ifndef SOAP_TYPE___ns1__wsh_USCOREupdate_
#define SOAP_TYPE___ns1__wsh_USCOREupdate_ (388)
/* Operation wrapper: */
struct __ns1__wsh_USCOREupdate_
{
	struct _ns1__wsh_USCOREupdate *ns1__wsh_USCOREupdate;	/* optional element of type ns1:wsh_update */
};
#endif

#ifndef SOAP_TYPE___ns1__tsf_USCOREupdate_
#define SOAP_TYPE___ns1__tsf_USCOREupdate_ (390)
/* Operation wrapper: */
struct __ns1__tsf_USCOREupdate_
{
	struct _ns1__tsf_USCOREupdate *ns1__tsf_USCOREupdate;	/* optional element of type ns1:tsf_update */
};
#endif

#ifndef SOAP_TYPE___ns1__ZB_USCORETZ_USCOREDay_
#define SOAP_TYPE___ns1__ZB_USCORETZ_USCOREDay_ (392)
/* Operation wrapper: */
struct __ns1__ZB_USCORETZ_USCOREDay_
{
	struct _ns1__ZB_USCORETZ_USCOREDay *ns1__ZB_USCORETZ_USCOREDay;	/* optional element of type ns1:ZB_TZ_Day */
};
#endif

#ifndef SOAP_TYPE___ns1__ZB_USCORETZ_USCOREMonth_
#define SOAP_TYPE___ns1__ZB_USCORETZ_USCOREMonth_ (394)
/* Operation wrapper: */
struct __ns1__ZB_USCORETZ_USCOREMonth_
{
	struct _ns1__ZB_USCORETZ_USCOREMonth *ns1__ZB_USCORETZ_USCOREMonth;	/* optional element of type ns1:ZB_TZ_Month */
};
#endif

#ifndef SOAP_TYPE___ns1__get_USCOREzbfp_
#define SOAP_TYPE___ns1__get_USCOREzbfp_ (396)
/* Operation wrapper: */
struct __ns1__get_USCOREzbfp_
{
	struct _ns1__get_USCOREzbfp *ns1__get_USCOREzbfp;	/* optional element of type ns1:get_zbfp */
};
#endif

#ifndef SOAP_TYPE___ns1__fp_USCOREdy_USCOREend_
#define SOAP_TYPE___ns1__fp_USCOREdy_USCOREend_ (398)
/* Operation wrapper: */
struct __ns1__fp_USCOREdy_USCOREend_
{
	struct _ns1__fp_USCOREdy_USCOREend *ns1__fp_USCOREdy_USCOREend;	/* optional element of type ns1:fp_dy_end */
};
#endif

#ifndef SOAP_TYPE___ns1__get_USCOREhbgs1_
#define SOAP_TYPE___ns1__get_USCOREhbgs1_ (400)
/* Operation wrapper: */
struct __ns1__get_USCOREhbgs1_
{
	struct _ns1__get_USCOREhbgs1 *ns1__get_USCOREhbgs1;	/* optional element of type ns1:get_hbgs1 */
};
#endif

#ifndef SOAP_TYPE___ns1__get_USCOREhbwsh1_
#define SOAP_TYPE___ns1__get_USCOREhbwsh1_ (402)
/* Operation wrapper: */
struct __ns1__get_USCOREhbwsh1_
{
	struct _ns1__get_USCOREhbwsh1 *ns1__get_USCOREhbwsh1;	/* optional element of type ns1:get_hbwsh1 */
};
#endif

#ifndef SOAP_TYPE___ns1__get_USCOREmx1_
#define SOAP_TYPE___ns1__get_USCOREmx1_ (404)
/* Operation wrapper: */
struct __ns1__get_USCOREmx1_
{
	struct _ns1__get_USCOREmx1 *ns1__get_USCOREmx1;	/* optional element of type ns1:get_mx1 */
};
#endif

#ifndef SOAP_TYPE___ns1__hbwsh_USCOREupdate1_
#define SOAP_TYPE___ns1__hbwsh_USCOREupdate1_ (406)
/* Operation wrapper: */
struct __ns1__hbwsh_USCOREupdate1_
{
	struct _ns1__hbwsh_USCOREupdate1 *ns1__hbwsh_USCOREupdate1;	/* optional element of type ns1:hbwsh_update1 */
};
#endif

#ifndef SOAP_TYPE___ns1__hbtsf_USCOREupdate1_
#define SOAP_TYPE___ns1__hbtsf_USCOREupdate1_ (408)
/* Operation wrapper: */
struct __ns1__hbtsf_USCOREupdate1_
{
	struct _ns1__hbtsf_USCOREupdate1 *ns1__hbtsf_USCOREupdate1;	/* optional element of type ns1:hbtsf_update1 */
};
#endif

#ifndef SOAP_TYPE___ns1__get_USCOREhbfp1_
#define SOAP_TYPE___ns1__get_USCOREhbfp1_ (410)
/* Operation wrapper: */
struct __ns1__get_USCOREhbfp1_
{
	struct _ns1__get_USCOREhbfp1 *ns1__get_USCOREhbfp1;	/* optional element of type ns1:get_hbfp1 */
};
#endif

#ifndef SOAP_TYPE___ns1__get_USCOREyyzd1_
#define SOAP_TYPE___ns1__get_USCOREyyzd1_ (412)
/* Operation wrapper: */
struct __ns1__get_USCOREyyzd1_
{
	struct _ns1__get_USCOREyyzd1 *ns1__get_USCOREyyzd1;	/* optional element of type ns1:get_yyzd1 */
};
#endif

#ifndef SOAP_TYPE___ns1__get_USCOREyue1_
#define SOAP_TYPE___ns1__get_USCOREyue1_ (414)
/* Operation wrapper: */
struct __ns1__get_USCOREyue1_
{
	struct _ns1__get_USCOREyue1 *ns1__get_USCOREyue1;	/* optional element of type ns1:get_yue1 */
};
#endif

#ifndef SOAP_TYPE___ns1__hb_USCOREfp_USCOREdy_USCOREend1_
#define SOAP_TYPE___ns1__hb_USCOREfp_USCOREdy_USCOREend1_ (416)
/* Operation wrapper: */
struct __ns1__hb_USCOREfp_USCOREdy_USCOREend1_
{
	struct _ns1__hb_USCOREfp_USCOREdy_USCOREend1 *ns1__hb_USCOREfp_USCOREdy_USCOREend1;	/* optional element of type ns1:hb_fp_dy_end1 */
};
#endif

#ifndef SOAP_TYPE___ns1__TZ_USCOREDay1_
#define SOAP_TYPE___ns1__TZ_USCOREDay1_ (418)
/* Operation wrapper: */
struct __ns1__TZ_USCOREDay1_
{
	struct _ns1__TZ_USCOREDay1 *ns1__TZ_USCOREDay1;	/* optional element of type ns1:TZ_Day1 */
};
#endif

#ifndef SOAP_TYPE___ns1__m_USCOREtz_USCOREupdate1_
#define SOAP_TYPE___ns1__m_USCOREtz_USCOREupdate1_ (420)
/* Operation wrapper: */
struct __ns1__m_USCOREtz_USCOREupdate1_
{
	struct _ns1__m_USCOREtz_USCOREupdate1 *ns1__m_USCOREtz_USCOREupdate1;	/* optional element of type ns1:m_tz_update1 */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (421)
/* SOAP Header: */
struct SOAP_ENV__Header
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (422)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (424)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
	char *__any;
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (427)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (428)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif

#ifndef SOAP_TYPE_xsd__decimal
#define SOAP_TYPE_xsd__decimal (12)
typedef char *xsd__decimal;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stubs                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetTime(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__GetTime *ns1__GetTime, struct _ns1__GetTimeResponse *ns1__GetTimeResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetDNS(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__GetDNS *ns1__GetDNS, struct _ns1__GetDNSResponse *ns1__GetDNSResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetHostInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__GetHostInfo *ns1__GetHostInfo, struct _ns1__GetHostInfoResponse *ns1__GetHostInfoResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__CheckSHA1(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__CheckSHA1 *ns1__CheckSHA1, struct _ns1__CheckSHA1Response *ns1__CheckSHA1Response);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__ToBASE64(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__ToBASE64 *ns1__ToBASE64, struct _ns1__ToBASE64Response *ns1__ToBASE64Response);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__FromBASE64(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__FromBASE64 *ns1__FromBASE64, struct _ns1__FromBASE64Response *ns1__FromBASE64Response);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__get_USCOREhbgs(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__get_USCOREhbgs *ns1__get_USCOREhbgs, struct _ns1__get_USCOREhbgsResponse *ns1__get_USCOREhbgsResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__get_USCOREhbwsh(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__get_USCOREhbwsh *ns1__get_USCOREhbwsh, struct _ns1__get_USCOREhbwshResponse *ns1__get_USCOREhbwshResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__get_USCOREmx(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__get_USCOREmx *ns1__get_USCOREmx, struct _ns1__get_USCOREmxResponse *ns1__get_USCOREmxResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__hbwsh_USCOREupdate(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__hbwsh_USCOREupdate *ns1__hbwsh_USCOREupdate, struct _ns1__hbwsh_USCOREupdateResponse *ns1__hbwsh_USCOREupdateResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__hbtsf_USCOREupdate(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__hbtsf_USCOREupdate *ns1__hbtsf_USCOREupdate, struct _ns1__hbtsf_USCOREupdateResponse *ns1__hbtsf_USCOREupdateResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__TZ_USCOREDay(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__TZ_USCOREDay *ns1__TZ_USCOREDay, struct _ns1__TZ_USCOREDayResponse *ns1__TZ_USCOREDayResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__TZ_USCOREMonth(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__TZ_USCOREMonth *ns1__TZ_USCOREMonth, struct _ns1__TZ_USCOREMonthResponse *ns1__TZ_USCOREMonthResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__m_USCOREtz_USCOREupdate(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__m_USCOREtz_USCOREupdate *ns1__m_USCOREtz_USCOREupdate, struct _ns1__m_USCOREtz_USCOREupdateResponse *ns1__m_USCOREtz_USCOREupdateResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__m_USCOREzb_USCOREtz_USCOREupdate(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__m_USCOREzb_USCOREtz_USCOREupdate *ns1__m_USCOREzb_USCOREtz_USCOREupdate, struct _ns1__m_USCOREzb_USCOREtz_USCOREupdateResponse *ns1__m_USCOREzb_USCOREtz_USCOREupdateResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__get_USCOREhbfp(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__get_USCOREhbfp *ns1__get_USCOREhbfp, struct _ns1__get_USCOREhbfpResponse *ns1__get_USCOREhbfpResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__get_USCOREyyzd(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__get_USCOREyyzd *ns1__get_USCOREyyzd, struct _ns1__get_USCOREyyzdResponse *ns1__get_USCOREyyzdResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__get_USCOREhbwsh_USCOREyue(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__get_USCOREhbwsh_USCOREyue *ns1__get_USCOREhbwsh_USCOREyue, struct _ns1__get_USCOREhbwsh_USCOREyueResponse *ns1__get_USCOREhbwsh_USCOREyueResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__get_USCOREyue(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__get_USCOREyue *ns1__get_USCOREyue, struct _ns1__get_USCOREyueResponse *ns1__get_USCOREyueResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__hbwsh_USCOREyue_USCOREupdate(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__hbwsh_USCOREyue_USCOREupdate *ns1__hbwsh_USCOREyue_USCOREupdate, struct _ns1__hbwsh_USCOREyue_USCOREupdateResponse *ns1__hbwsh_USCOREyue_USCOREupdateResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__hbtsf_USCOREyue_USCOREupdate(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__hbtsf_USCOREyue_USCOREupdate *ns1__hbtsf_USCOREyue_USCOREupdate, struct _ns1__hbtsf_USCOREyue_USCOREupdateResponse *ns1__hbtsf_USCOREyue_USCOREupdateResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__hb_USCOREfp_USCOREdy_USCOREend(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__hb_USCOREfp_USCOREdy_USCOREend *ns1__hb_USCOREfp_USCOREdy_USCOREend, struct _ns1__hb_USCOREfp_USCOREdy_USCOREendResponse *ns1__hb_USCOREfp_USCOREdy_USCOREendResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__get_USCOREwsh(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__get_USCOREwsh *ns1__get_USCOREwsh, struct _ns1__get_USCOREwshResponse *ns1__get_USCOREwshResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__get_USCOREzb_USCOREmx(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__get_USCOREzb_USCOREmx *ns1__get_USCOREzb_USCOREmx, struct _ns1__get_USCOREzb_USCOREmxResponse *ns1__get_USCOREzb_USCOREmxResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__wsh_USCOREupdate(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__wsh_USCOREupdate *ns1__wsh_USCOREupdate, struct _ns1__wsh_USCOREupdateResponse *ns1__wsh_USCOREupdateResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__tsf_USCOREupdate(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__tsf_USCOREupdate *ns1__tsf_USCOREupdate, struct _ns1__tsf_USCOREupdateResponse *ns1__tsf_USCOREupdateResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__ZB_USCORETZ_USCOREDay(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__ZB_USCORETZ_USCOREDay *ns1__ZB_USCORETZ_USCOREDay, struct _ns1__ZB_USCORETZ_USCOREDayResponse *ns1__ZB_USCORETZ_USCOREDayResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__ZB_USCORETZ_USCOREMonth(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__ZB_USCORETZ_USCOREMonth *ns1__ZB_USCORETZ_USCOREMonth, struct _ns1__ZB_USCORETZ_USCOREMonthResponse *ns1__ZB_USCORETZ_USCOREMonthResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__get_USCOREzbfp(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__get_USCOREzbfp *ns1__get_USCOREzbfp, struct _ns1__get_USCOREzbfpResponse *ns1__get_USCOREzbfpResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__fp_USCOREdy_USCOREend(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__fp_USCOREdy_USCOREend *ns1__fp_USCOREdy_USCOREend, struct _ns1__fp_USCOREdy_USCOREendResponse *ns1__fp_USCOREdy_USCOREendResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__get_USCOREhbgs1(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__get_USCOREhbgs1 *ns1__get_USCOREhbgs1, struct _ns1__get_USCOREhbgs1Response *ns1__get_USCOREhbgs1Response);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__get_USCOREhbwsh1(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__get_USCOREhbwsh1 *ns1__get_USCOREhbwsh1, struct _ns1__get_USCOREhbwsh1Response *ns1__get_USCOREhbwsh1Response);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__get_USCOREmx1(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__get_USCOREmx1 *ns1__get_USCOREmx1, struct _ns1__get_USCOREmx1Response *ns1__get_USCOREmx1Response);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__hbwsh_USCOREupdate1(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__hbwsh_USCOREupdate1 *ns1__hbwsh_USCOREupdate1, struct _ns1__hbwsh_USCOREupdate1Response *ns1__hbwsh_USCOREupdate1Response);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__hbtsf_USCOREupdate1(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__hbtsf_USCOREupdate1 *ns1__hbtsf_USCOREupdate1, struct _ns1__hbtsf_USCOREupdate1Response *ns1__hbtsf_USCOREupdate1Response);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__get_USCOREhbfp1(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__get_USCOREhbfp1 *ns1__get_USCOREhbfp1, struct _ns1__get_USCOREhbfp1Response *ns1__get_USCOREhbfp1Response);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__get_USCOREyyzd1(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__get_USCOREyyzd1 *ns1__get_USCOREyyzd1, struct _ns1__get_USCOREyyzd1Response *ns1__get_USCOREyyzd1Response);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__get_USCOREyue1(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__get_USCOREyue1 *ns1__get_USCOREyue1, struct _ns1__get_USCOREyue1Response *ns1__get_USCOREyue1Response);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__hb_USCOREfp_USCOREdy_USCOREend1(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__hb_USCOREfp_USCOREdy_USCOREend1 *ns1__hb_USCOREfp_USCOREdy_USCOREend1, struct _ns1__hb_USCOREfp_USCOREdy_USCOREend1Response *ns1__hb_USCOREfp_USCOREdy_USCOREend1Response);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__TZ_USCOREDay1(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__TZ_USCOREDay1 *ns1__TZ_USCOREDay1, struct _ns1__TZ_USCOREDay1Response *ns1__TZ_USCOREDay1Response);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__m_USCOREtz_USCOREupdate1(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__m_USCOREtz_USCOREupdate1 *ns1__m_USCOREtz_USCOREupdate1, struct _ns1__m_USCOREtz_USCOREupdate1Response *ns1__m_USCOREtz_USCOREupdate1Response);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetTime_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__GetTime *ns1__GetTime, struct _ns1__GetTimeResponse *ns1__GetTimeResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetDNS_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__GetDNS *ns1__GetDNS, struct _ns1__GetDNSResponse *ns1__GetDNSResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetHostInfo_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__GetHostInfo *ns1__GetHostInfo, struct _ns1__GetHostInfoResponse *ns1__GetHostInfoResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__CheckSHA1_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__CheckSHA1 *ns1__CheckSHA1, struct _ns1__CheckSHA1Response *ns1__CheckSHA1Response);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__ToBASE64_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__ToBASE64 *ns1__ToBASE64, struct _ns1__ToBASE64Response *ns1__ToBASE64Response);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__FromBASE64_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__FromBASE64 *ns1__FromBASE64, struct _ns1__FromBASE64Response *ns1__FromBASE64Response);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__get_USCOREhbgs_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__get_USCOREhbgs *ns1__get_USCOREhbgs, struct _ns1__get_USCOREhbgsResponse *ns1__get_USCOREhbgsResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__get_USCOREhbwsh_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__get_USCOREhbwsh *ns1__get_USCOREhbwsh, struct _ns1__get_USCOREhbwshResponse *ns1__get_USCOREhbwshResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__get_USCOREmx_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__get_USCOREmx *ns1__get_USCOREmx, struct _ns1__get_USCOREmxResponse *ns1__get_USCOREmxResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__hbwsh_USCOREupdate_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__hbwsh_USCOREupdate *ns1__hbwsh_USCOREupdate, struct _ns1__hbwsh_USCOREupdateResponse *ns1__hbwsh_USCOREupdateResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__hbtsf_USCOREupdate_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__hbtsf_USCOREupdate *ns1__hbtsf_USCOREupdate, struct _ns1__hbtsf_USCOREupdateResponse *ns1__hbtsf_USCOREupdateResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__TZ_USCOREDay_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__TZ_USCOREDay *ns1__TZ_USCOREDay, struct _ns1__TZ_USCOREDayResponse *ns1__TZ_USCOREDayResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__TZ_USCOREMonth_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__TZ_USCOREMonth *ns1__TZ_USCOREMonth, struct _ns1__TZ_USCOREMonthResponse *ns1__TZ_USCOREMonthResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__m_USCOREtz_USCOREupdate_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__m_USCOREtz_USCOREupdate *ns1__m_USCOREtz_USCOREupdate, struct _ns1__m_USCOREtz_USCOREupdateResponse *ns1__m_USCOREtz_USCOREupdateResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__m_USCOREzb_USCOREtz_USCOREupdate_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__m_USCOREzb_USCOREtz_USCOREupdate *ns1__m_USCOREzb_USCOREtz_USCOREupdate, struct _ns1__m_USCOREzb_USCOREtz_USCOREupdateResponse *ns1__m_USCOREzb_USCOREtz_USCOREupdateResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__get_USCOREhbfp_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__get_USCOREhbfp *ns1__get_USCOREhbfp, struct _ns1__get_USCOREhbfpResponse *ns1__get_USCOREhbfpResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__get_USCOREyyzd_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__get_USCOREyyzd *ns1__get_USCOREyyzd, struct _ns1__get_USCOREyyzdResponse *ns1__get_USCOREyyzdResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__get_USCOREhbwsh_USCOREyue_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__get_USCOREhbwsh_USCOREyue *ns1__get_USCOREhbwsh_USCOREyue, struct _ns1__get_USCOREhbwsh_USCOREyueResponse *ns1__get_USCOREhbwsh_USCOREyueResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__get_USCOREyue_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__get_USCOREyue *ns1__get_USCOREyue, struct _ns1__get_USCOREyueResponse *ns1__get_USCOREyueResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__hbwsh_USCOREyue_USCOREupdate_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__hbwsh_USCOREyue_USCOREupdate *ns1__hbwsh_USCOREyue_USCOREupdate, struct _ns1__hbwsh_USCOREyue_USCOREupdateResponse *ns1__hbwsh_USCOREyue_USCOREupdateResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__hbtsf_USCOREyue_USCOREupdate_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__hbtsf_USCOREyue_USCOREupdate *ns1__hbtsf_USCOREyue_USCOREupdate, struct _ns1__hbtsf_USCOREyue_USCOREupdateResponse *ns1__hbtsf_USCOREyue_USCOREupdateResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__hb_USCOREfp_USCOREdy_USCOREend_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__hb_USCOREfp_USCOREdy_USCOREend *ns1__hb_USCOREfp_USCOREdy_USCOREend, struct _ns1__hb_USCOREfp_USCOREdy_USCOREendResponse *ns1__hb_USCOREfp_USCOREdy_USCOREendResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__get_USCOREwsh_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__get_USCOREwsh *ns1__get_USCOREwsh, struct _ns1__get_USCOREwshResponse *ns1__get_USCOREwshResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__get_USCOREzb_USCOREmx_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__get_USCOREzb_USCOREmx *ns1__get_USCOREzb_USCOREmx, struct _ns1__get_USCOREzb_USCOREmxResponse *ns1__get_USCOREzb_USCOREmxResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__wsh_USCOREupdate_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__wsh_USCOREupdate *ns1__wsh_USCOREupdate, struct _ns1__wsh_USCOREupdateResponse *ns1__wsh_USCOREupdateResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__tsf_USCOREupdate_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__tsf_USCOREupdate *ns1__tsf_USCOREupdate, struct _ns1__tsf_USCOREupdateResponse *ns1__tsf_USCOREupdateResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__ZB_USCORETZ_USCOREDay_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__ZB_USCORETZ_USCOREDay *ns1__ZB_USCORETZ_USCOREDay, struct _ns1__ZB_USCORETZ_USCOREDayResponse *ns1__ZB_USCORETZ_USCOREDayResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__ZB_USCORETZ_USCOREMonth_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__ZB_USCORETZ_USCOREMonth *ns1__ZB_USCORETZ_USCOREMonth, struct _ns1__ZB_USCORETZ_USCOREMonthResponse *ns1__ZB_USCORETZ_USCOREMonthResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__get_USCOREzbfp_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__get_USCOREzbfp *ns1__get_USCOREzbfp, struct _ns1__get_USCOREzbfpResponse *ns1__get_USCOREzbfpResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__fp_USCOREdy_USCOREend_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__fp_USCOREdy_USCOREend *ns1__fp_USCOREdy_USCOREend, struct _ns1__fp_USCOREdy_USCOREendResponse *ns1__fp_USCOREdy_USCOREendResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__get_USCOREhbgs1_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__get_USCOREhbgs1 *ns1__get_USCOREhbgs1, struct _ns1__get_USCOREhbgs1Response *ns1__get_USCOREhbgs1Response);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__get_USCOREhbwsh1_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__get_USCOREhbwsh1 *ns1__get_USCOREhbwsh1, struct _ns1__get_USCOREhbwsh1Response *ns1__get_USCOREhbwsh1Response);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__get_USCOREmx1_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__get_USCOREmx1 *ns1__get_USCOREmx1, struct _ns1__get_USCOREmx1Response *ns1__get_USCOREmx1Response);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__hbwsh_USCOREupdate1_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__hbwsh_USCOREupdate1 *ns1__hbwsh_USCOREupdate1, struct _ns1__hbwsh_USCOREupdate1Response *ns1__hbwsh_USCOREupdate1Response);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__hbtsf_USCOREupdate1_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__hbtsf_USCOREupdate1 *ns1__hbtsf_USCOREupdate1, struct _ns1__hbtsf_USCOREupdate1Response *ns1__hbtsf_USCOREupdate1Response);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__get_USCOREhbfp1_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__get_USCOREhbfp1 *ns1__get_USCOREhbfp1, struct _ns1__get_USCOREhbfp1Response *ns1__get_USCOREhbfp1Response);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__get_USCOREyyzd1_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__get_USCOREyyzd1 *ns1__get_USCOREyyzd1, struct _ns1__get_USCOREyyzd1Response *ns1__get_USCOREyyzd1Response);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__get_USCOREyue1_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__get_USCOREyue1 *ns1__get_USCOREyue1, struct _ns1__get_USCOREyue1Response *ns1__get_USCOREyue1Response);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__hb_USCOREfp_USCOREdy_USCOREend1_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__hb_USCOREfp_USCOREdy_USCOREend1 *ns1__hb_USCOREfp_USCOREdy_USCOREend1, struct _ns1__hb_USCOREfp_USCOREdy_USCOREend1Response *ns1__hb_USCOREfp_USCOREdy_USCOREend1Response);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__TZ_USCOREDay1_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__TZ_USCOREDay1 *ns1__TZ_USCOREDay1, struct _ns1__TZ_USCOREDay1Response *ns1__TZ_USCOREDay1Response);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__m_USCOREtz_USCOREupdate1_(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__m_USCOREtz_USCOREupdate1 *ns1__m_USCOREtz_USCOREupdate1, struct _ns1__m_USCOREtz_USCOREupdate1Response *ns1__m_USCOREtz_USCOREupdate1Response);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapStub.h */
