######################################################################
# Automatically generated by qmake (2.01a) Tue May 15 22:13:27 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += teamleadersdialog.h
SOURCES += main.cpp teamleadersdialog.cpp
