######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 25 00:04:05 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += sortdialog.h
FORMS += sortdialog.ui
SOURCES += main.cpp sortdialog.cpp
