######################################################################
# Automatically generated by qmake (2.01a) Wed May 30 18:30:53 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += table.h
SOURCES += main.cpp table.cpp
RESOURCES += table.qrc
TRANSLATIONS += table_zh.ts
