######################################################################
# Automatically generated by qmake (2.01a) Tue May 22 13:55:16 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += thread.h threaddialog.h
SOURCES += main.cpp thread.cpp threaddialog.cpp
