######################################################################
# Automatically generated by qmake (2.01a) Sat May 19 13:27:51 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += currencymodel.h
SOURCES += currencymodel.cpp main.cpp
