######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 4 20:14:20 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += coordinatesetter.h
SOURCES += coordinatesetter.cpp main.cpp
