######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 25 14:26:38 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gotocelldialog.h
FORMS += gotocelldialog.ui
SOURCES += gotocelldialog.cpp main.cpp
