######################################################################
# Automatically generated by qmake (2.01a) Wed Jun 6 11:53:31 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += fileviewer.h
SOURCES += fileviewer.cpp main.cpp
RESOURCES += fileviewer.qrc
TRANSLATIONS += fileviewer_zh.ts
