######################################################################
# Automatically generated by qmake (2.01a) ?? 11? 13 02:18:39 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += standarddialogs.h
SOURCES += main.cc standarddialogs.cpp
