######################################################################
# Automatically generated by qmake (2.01a) Wed May 30 18:17:49 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += drawer.h
SOURCES += drawer.cpp main.cpp
RESOURCES += drawer.qrc
TRANSLATIONS += drawer_zh.ts
