######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 24 18:42:53 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += gotocell.h
FORMS += gotocell.ui
SOURCES += gotocell.cpp main.cpp
