######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 24 11:51:44 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
